
--> Seed editorial aprovado para o catálogo Shadowlords.
INSERT INTO `rpgSystems` (`id`, `name`, `edition`, `status`) VALUES ('shadowlords', 'Shadowlords Mini System', 'Edição de campanha', 'active') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `edition` = VALUES(`edition`), `status` = VALUES(`status`);
INSERT INTO `campaignBlessings` (`ownerId`, `campaignId`, `systemId`, `name`, `summary`, `effect`, `sourceLabel`, `visibility`) SELECT NULL, NULL, 'shadowlords', 'Mão do Curador', 'Uma bênção de cuidado e primeiros socorros.', 'Uma vez por cena, ao tratar um aliado, restaura 1d3 PV adicionais ou encerra Sangramento.', 'Bênçãos e regras complementares de Shadowlords', 'public' WHERE NOT EXISTS (SELECT 1 FROM `campaignBlessings` WHERE `systemId` = 'shadowlords' AND `name` = 'Mão do Curador');
INSERT INTO `campaignBlessings` (`ownerId`, `campaignId`, `systemId`, `name`, `summary`, `effect`, `sourceLabel`, `visibility`) SELECT NULL, NULL, 'shadowlords', 'Olhos do Peregrino', 'A bênção dos que encontram abrigo nas estradas.', '+1 em um Teste de Sabedoria para encontrar abrigo, rastros ou uma rota segura por trecho.', 'Bênçãos e regras complementares de Shadowlords', 'public' WHERE NOT EXISTS (SELECT 1 FROM `campaignBlessings` WHERE `systemId` = 'shadowlords' AND `name` = 'Olhos do Peregrino');
INSERT INTO `campaignBlessings` (`ownerId`, `campaignId`, `systemId`, `name`, `summary`, `effect`, `sourceLabel`, `visibility`) SELECT NULL, NULL, 'shadowlords', 'Fôlego de Ferro', 'Resistência para atravessar terreno sob peso.', 'Uma vez por aventura, ignore a penalidade de uma armadura pesada em um teste de terreno difícil.', 'Bênçãos e regras complementares de Shadowlords', 'public' WHERE NOT EXISTS (SELECT 1 FROM `campaignBlessings` WHERE `systemId` = 'shadowlords' AND `name` = 'Fôlego de Ferro');
INSERT INTO `campaignBlessings` (`ownerId`, `campaignId`, `systemId`, `name`, `summary`, `effect`, `sourceLabel`, `visibility`) SELECT NULL, NULL, 'shadowlords', 'Passo Silencioso', 'A bênção de quem atravessa ruínas sem alimentar o ruído.', 'A primeira falha em Ocultação ou Manha durante uma cena não produz Ruído adicional.', 'Bênçãos e regras complementares de Shadowlords', 'public' WHERE NOT EXISTS (SELECT 1 FROM `campaignBlessings` WHERE `systemId` = 'shadowlords' AND `name` = 'Passo Silencioso');
INSERT INTO `campaignBlessings` (`ownerId`, `campaignId`, `systemId`, `name`, `summary`, `effect`, `sourceLabel`, `visibility`) SELECT NULL, NULL, 'shadowlords', 'Lâmpada de Quézza', 'Um sinal de lealdade à proteção de Arys.', 'Uma vez por cena, revela uma passagem escondida, símbolo de culto ou objeto corrompido a até 5 metros.', 'Bênçãos e regras complementares de Shadowlords', 'public' WHERE NOT EXISTS (SELECT 1 FROM `campaignBlessings` WHERE `systemId` = 'shadowlords' AND `name` = 'Lâmpada de Quézza');
INSERT INTO `campaignBlessings` (`ownerId`, `campaignId`, `systemId`, `name`, `summary`, `effect`, `sourceLabel`, `visibility`) SELECT NULL, NULL, 'shadowlords', 'Selo da Guarda Real', 'O distintivo que transforma proteção em voto.', '+1 Defesa durante a primeira rodada de um combate em que você esteja protegendo um aliado ou uma autoridade.', 'Bênçãos e regras complementares de Shadowlords', 'public' WHERE NOT EXISTS (SELECT 1 FROM `campaignBlessings` WHERE `systemId` = 'shadowlords' AND `name` = 'Selo da Guarda Real');
INSERT INTO `campaignBlessings` (`ownerId`, `campaignId`, `systemId`, `name`, `summary`, `effect`, `sourceLabel`, `visibility`) SELECT NULL, NULL, 'shadowlords', 'Portadora da Chama', 'A chama que encara sombras e demônios.', 'Uma vez por cena, concede +1 em um teste contra mortos-vivos ou demônios; a chama não pode ser escondida de criaturas sensíveis à luz.', 'Bênçãos e regras complementares de Shadowlords', 'public' WHERE NOT EXISTS (SELECT 1 FROM `campaignBlessings` WHERE `systemId` = 'shadowlords' AND `name` = 'Portadora da Chama');
INSERT INTO `campaignBlessings` (`ownerId`, `campaignId`, `systemId`, `name`, `summary`, `effect`, `sourceLabel`, `visibility`) SELECT NULL, NULL, 'shadowlords', 'Companheiro das Estradas', 'Um pacto de cuidado com as montarias e os caminhos.', 'A montaria recebe +1 em um teste de terreno por trecho; sem montaria, você recebe +1 em Sobrevivência.', 'Bênçãos e regras complementares de Shadowlords', 'public' WHERE NOT EXISTS (SELECT 1 FROM `campaignBlessings` WHERE `systemId` = 'shadowlords' AND `name` = 'Companheiro das Estradas');
