import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { buildLibraryFilters, creatureTypeLabels, rpgSystemLabels, threatLevelLabels, type LibraryCreatureFilter, type LibrarySystemFilter, type LibraryThreatFilter } from "@shared/library";
import { BookMarked, ExternalLink, Filter, Skull, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";

const sourceCategoryLabels: Record<string, string> = { guide: "guia", setting: "cenário", antagonist: "dossiê", rules: "regras", supplement: "suplemento", folder: "pasta", asset: "artefato" };
const sourceStatusLabels: Record<string, string> = { referenced: "referenciado", cataloged: "catalogado", integrated: "integrado" };

function AntagonistLibraryContent() {
  const [systemId, setSystemId] = useState<LibrarySystemFilter>("all");
  const [creatureType, setCreatureType] = useState<LibraryCreatureFilter>("all");
  const [threatLevel, setThreatLevel] = useState<LibraryThreatFilter>("all");
  const filters = useMemo(() => buildLibraryFilters({ systemId, creatureType, threatLevel }), [systemId, creatureType, threatLevel]);
  const { data: antagonists = [], isLoading } = trpc.library.antagonists.useQuery(filters);
  const { data: sources = [] } = trpc.library.sources.useQuery();

  return <div className="min-h-screen bg-[#101211] text-[#eae3d5]"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><header className="border-b border-white/10 pb-7"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#83a89a]">Biblioteca de ameaças · consulta 06</p><div className="mt-3 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h1 className="font-serif text-5xl leading-none tracking-[-0.04em] text-[#f4eee4]">Antagonistas<br />sob custódia.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#b8b3a8]">Dossiês organizados por natureza e perigo. Os registros iniciais foram extraídos dos materiais de crônica compartilhados e conservam a ligação com sua fonte.</p></div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.15em] text-[#d27648]"><Skull className="h-4 w-4" /> {antagonists.length} registros consultáveis</div></div></header>

  <section className="mt-7 border border-[#b55b32]/40 bg-[#171a18] p-5"><div className="flex items-center justify-between gap-4 text-[10px] font-bold uppercase tracking-[0.18em] text-[#a9c7bb]"><span className="flex items-center gap-2"><Filter className="h-4 w-4 text-[#d27648]" /> Formulário de consulta</span><span className="text-[#d27648]">Gaveta 01 · acesso controlado</span></div><div className="mt-4 grid gap-3 border-t border-dashed border-white/15 pt-4 md:grid-cols-3"><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Sistema<select value={systemId} onChange={(event) => setSystemId(event.target.value as LibrarySystemFilter)} className="h-11 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5] outline-none focus:border-[#b55b32]"><option value="all">Todos os sistemas</option>{Object.entries(rpgSystemLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Tipo de criatura<select value={creatureType} onChange={(event) => setCreatureType(event.target.value as LibraryCreatureFilter)} className="h-11 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5] outline-none focus:border-[#b55b32]"><option value="all">Todos os tipos</option>{Object.entries(creatureTypeLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Nível de ameaça<select value={threatLevel} onChange={(event) => setThreatLevel(event.target.value as LibraryThreatFilter)} className="h-11 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5] outline-none focus:border-[#b55b32]"><option value="all">Todos os níveis</option>{Object.entries(threatLevelLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div></section>

  <section className="mt-7 grid gap-4 lg:grid-cols-2">{isLoading ? <p className="text-sm text-[#b8b3a8]">Abrindo fichário de ameaças…</p> : antagonists.length ? antagonists.map((antagonist) => <article key={antagonist.id} className={`relative overflow-hidden border border-white/10 bg-[#171a18] p-6 ${antagonist.threatLevel === "cataclysmic" ? "lg:col-span-2 lg:grid lg:grid-cols-[0.8fr_1.2fr] lg:gap-8" : ""}`}><div className="absolute inset-0 dossier-grid opacity-15" /><div className="relative"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#83a89a]">{rpgSystemLabels[antagonist.systemId as keyof typeof rpgSystemLabels] || antagonist.systemId}</p><h2 className="mt-3 font-serif text-3xl leading-none text-[#f4eee4]">{antagonist.name}</h2></div><span className="border border-[#b55b32]/70 px-2 py-1 text-[9px] font-bold uppercase tracking-[0.12em] text-[#ffb08e]">{threatLevelLabels[antagonist.threatLevel as keyof typeof threatLevelLabels]}</span></div><p className="mt-4 text-sm leading-6 text-[#c7c1b5]">{antagonist.summary}</p></div><div className="relative"><div className="mt-5 border-l border-[#83a89a]/55 pl-4"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]">Ganchos de entrada</p><ul className="mt-2 space-y-1 text-sm leading-5 text-[#eae3d5]">{(antagonist.hooks || []).map((hook) => <li key={hook}>— {hook}</li>)}</ul></div><div className="mt-5 flex items-center justify-between gap-3 border-t border-white/10 pt-4 text-[9px] font-bold uppercase tracking-[0.13em]"><span className="text-[#a9c7bb]">{creatureTypeLabels[antagonist.creatureType as keyof typeof creatureTypeLabels]}</span>{antagonist.sourceUrl ? <a className="flex items-center gap-1 text-[#d27648] hover:text-[#ffb08e]" href={antagonist.sourceUrl} target="_blank" rel="noreferrer">Fonte: {antagonist.sourceTitle || "Drive"}<ExternalLink className="h-3 w-3" /></a> : null}</div></div></article>) : <div className="border border-dashed border-white/20 p-8 text-sm leading-6 text-[#b8b3a8]">Nenhum dossiê corresponde a esta combinação de filtros. Ajuste a natureza ou a ameaça para reabrir o fichário.</div>}</section>

  <section className="mt-9 border-t border-white/10 pt-6"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-[#a9c7bb]"><BookMarked className="h-4 w-4 text-[#d27648]" /> Materiais preservados no Drive</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{sources.map((source) => <a key={source.id} href={source.sourceUrl} target="_blank" rel="noreferrer" className="group border border-white/10 bg-white/[0.025] p-4 transition-colors hover:border-[#b55b32]/60 hover:bg-[#b55b32]/5"><div className="flex items-start justify-between gap-3"><div><p className="font-serif text-xl leading-none text-[#f4eee4]">{source.title}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[0.13em] text-[#83a89a]">{sourceCategoryLabels[source.category] || "registro"} · {sourceStatusLabels[source.integrationStatus] || source.integrationStatus}</p></div><Sparkles className="h-4 w-4 shrink-0 text-[#d27648]" /></div><p className="mt-3 text-xs leading-5 text-[#b8b3a8]">{source.notes || "Registro preservado para consulta."}</p></a>)}</div></section></div></div>;
}

export default function AntagonistLibrary() { return <DashboardLayout><AntagonistLibraryContent /></DashboardLayout>; }
