import DashboardLayout from "@/components/DashboardLayout";
import { AttributeRuleTooltip, SystemRuleTooltip } from "@/components/SystemRuleTooltip";
import { SheetSystemSwitcher } from "@/components/SheetSystemSwitcher";
import { SheetCreationGuide } from "@/components/SheetCreationGuide";
import { QuickRollPanel, type QuickRollOption } from "@/components/QuickRollPanel";
import { CustomArchetypePanel } from "@/components/CustomArchetypePanel";
import { CharacterShareLinkButton } from "@/components/CharacterShareLinkButton";
import { DiceRollHistorySheet } from "@/components/DiceRollHistorySheet";
import { DiceRollFeedback, DiceRollInProgress } from "@/components/DiceRollFeedback";
import { DiceSoundControl, useDiceRollSound } from "@/components/DiceSoundControl";
import { DiceStyleControl, useDiceStyle } from "@/components/DiceStyleControl";
import { getTemporaryModifierTotal, TemporaryModifiersPanel } from "@/components/TemporaryModifiersPanel";
import type { TemporaryModifier } from "@shared/vampire-v5";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { getRpgSystem } from "@shared/rpg-systems";
import { BookOpen, CheckCircle2, ChevronDown, ChevronUp, Dice6, Heart, LoaderCircle, Moon, Plus, Save, Sparkles, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const ONE_RING = getRpgSystem("o-um-anel")!;
type OneRingSheetData = { culture: string; calling: string; shadowPath: string; attributes: Record<string, number>; skills: Record<string, number>; endurance: number; hope: number; shadow: number; notes: string; temporaryModifiers: TemporaryModifier[] };

function createOneRingSheetData(): OneRingSheetData {
  return { culture: "", calling: "", shadowPath: "", attributes: { strength: 2, heart: 2, wits: 2 }, skills: Object.fromEntries(ONE_RING.skills.map((skill) => [skill.id, 0])), endurance: 24, hope: 8, shadow: 0, notes: "", temporaryModifiers: [] };
}

function hydrateSheet(value: unknown): OneRingSheetData {
  const base = createOneRingSheetData();
  const raw = (value || {}) as Partial<OneRingSheetData>;
  return { ...base, ...raw, attributes: { ...base.attributes, ...(raw.attributes || {}) }, skills: { ...base.skills, ...(raw.skills || {}) }, temporaryModifiers: raw.temporaryModifiers || [] };
}

function OneRingSheetContent() {
  const utils = trpc.useUtils();
  const { data: characters = [], isLoading: loadingCharacters, error: charactersError } = trpc.characters.mine.useQuery();
  const { data: campaigns = [], isLoading: loadingCampaigns, error: campaignsError } = trpc.campaigns.mine.useQuery();
  const fellowship = useMemo(() => characters.filter((character) => character.systemId === "o-um-anel"), [characters]);
  const oneRingCampaigns = useMemo(() => campaigns.filter((campaign) => campaign.systemId === "o-um-anel"), [campaigns]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [name, setName] = useState("");
  const [concept, setConcept] = useState("");
  const [campaignId, setCampaignId] = useState("");
  const [sheet, setSheet] = useState<OneRingSheetData>(() => createOneRingSheetData());
  const [lastSavedAt, setLastSavedAt] = useState<Date | null>(null);
  const [quickRollResult, setQuickRollResult] = useState<{ label: string; target: number; featDie: number; skillDice: number[]; successes: number; modifier: number } | null>(null);
  const [rollingQuickRoll, setRollingQuickRoll] = useState<{ label: string; diceCount: number; modifier: number } | null>(null);
  const { enabled: diceSoundEnabled, setEnabled: setDiceSoundEnabled, volume: diceSoundVolume, setVolume: setDiceSoundVolume, playDiceSound } = useDiceRollSound();
  const { diceStyle, setDiceStyle } = useDiceStyle();
  const createCharacter = trpc.characters.create.useMutation({ onSuccess: async (created) => { await utils.characters.mine.invalidate(); setSelectedId(created.id); setLastSavedAt(new Date()); toast.success("Ficha de O Um Anel preservada no arquivo."); }, onError: (error) => toast.error(error.message) });
  const updateCharacter = trpc.characters.update.useMutation({ onSuccess: async () => { await utils.characters.mine.invalidate(); setLastSavedAt(new Date()); toast.success("Ficha de O Um Anel atualizada."); }, onError: (error) => toast.error(error.message) });
  const recordRoll = trpc.characters.recordRoll.useMutation({ onError: (error) => toast.error(error.message) });
  const openCharacter = (character: typeof fellowship[number]) => { setSelectedId(character.id); setName(character.name); setConcept(character.concept || ""); setCampaignId(character.campaignId ? String(character.campaignId) : ""); setSheet(hydrateSheet(character.sheetData)); };
  const newCharacter = () => { setSelectedId(null); setName(""); setConcept(""); setCampaignId(""); setSheet(createOneRingSheetData()); };
  const changeTrait = (group: "attributes" | "skills", id: string, delta: number, min: number, max: number) => setSheet((current) => ({ ...current, [group]: { ...current[group], [id]: Math.min(max, Math.max(min, (current[group][id] ?? min) + delta)) } }));
  const save = () => { if (name.trim().length < 2) { toast.error("Informe o nome do companheiro."); return; } const input = { name: name.trim(), concept: concept.trim() || undefined, campaignId: campaignId ? Number(campaignId) : null, sheetData: sheet }; if (selectedId) updateCharacter.mutate({ ...input, characterId: selectedId }); else createCharacter.mutate({ ...input, systemId: "o-um-anel" }); };
  const directRollOptions = [...ONE_RING.attributes.map((trait) => ({ id: `attribute:${trait.id}`, label: trait.label, detail: "Atributo" })), ...ONE_RING.skills.map((trait) => ({ id: `skill:${trait.id}`, label: trait.label, detail: "Perícia" }))];
  const revealQuickRoll = (result: { label: string; target: number; featDie: number; skillDice: number[]; successes: number; modifier: number }) => { playDiceSound(); setQuickRollResult(null); setRollingQuickRoll({ label: result.label, diceCount: result.skillDice.length + 1, modifier: result.modifier }); window.setTimeout(() => { setQuickRollResult(result); setRollingQuickRoll(null); }, 420); };
  const rollTrait = (option: QuickRollOption) => { const [kind, id] = option.id.split(":"); const scope = kind === "attribute" ? "attributes" : "skills"; const modifier = getTemporaryModifierTotal(sheet.temporaryModifiers, scope); const target = Math.max(1, ((scope === "attributes" ? sheet.attributes : sheet.skills)[id] || 0) + modifier); const featDie = Math.floor(Math.random() * 12) + 1; const skillDice = scope === "skills" ? Array.from({ length: Math.max(0, sheet.skills[id] || 0) }, () => Math.floor(Math.random() * 6) + 1) : []; const successes = (featDie >= target ? 1 : 0) + skillDice.filter((die) => die >= 6).length; const result = { label: option.label, target, featDie, skillDice, successes, modifier }; revealQuickRoll(result); if (selectedId) recordRoll.mutate({ systemId: "o-um-anel", characterId: selectedId, campaignId: campaignId ? Number(campaignId) : null, context: `${option.label} · modificador ${modifier >= 0 ? "+" : ""}${modifier}`, resultData: { ...result, scope } }); };
  const performQuickRoll = (option: QuickRollOption) => { const pairs: Record<string, ["strength" | "heart" | "wits", string]> = { travessia: ["strength", "travel"], vigia: ["wits", "awareness"], cacada: ["strength", "hunting"], canção: ["heart", "song"], presenca: ["heart", "awe"] }; const [attribute, skill] = pairs[option.id] || ["wits", "awareness"]; const modifier = getTemporaryModifierTotal(sheet.temporaryModifiers, "test"); const target = Math.max(1, (sheet.attributes[attribute] || 1) + modifier); const featDie = Math.floor(Math.random() * 12) + 1; const skillDice = Array.from({ length: Math.max(0, sheet.skills[skill] || 0) }, () => Math.floor(Math.random() * 6) + 1); const successes = (featDie >= target ? 1 : 0) + skillDice.filter((die) => die >= 6).length; const result = { label: option.label, target, featDie, skillDice, successes, modifier }; revealQuickRoll(result); if (selectedId) recordRoll.mutate({ systemId: "o-um-anel", characterId: selectedId, campaignId: campaignId ? Number(campaignId) : null, context: `${option.label} · modificador ${modifier >= 0 ? "+" : ""}${modifier}`, resultData: { ...result, attribute, skill } }); };
  const applyCustomArchetype = (payload: Record<string, unknown>, title: string) => { const template = payload as Partial<OneRingSheetData>; setSheet((current) => ({ ...current, culture: typeof template.culture === "string" ? template.culture : current.culture, calling: typeof template.calling === "string" ? template.calling : current.calling, shadowPath: typeof template.shadowPath === "string" ? template.shadowPath : current.shadowPath, attributes: { ...current.attributes, ...(template.attributes || {}) }, skills: { ...current.skills, ...(template.skills || {}) }, endurance: typeof template.endurance === "number" ? template.endurance : current.endurance, hope: typeof template.hope === "number" ? template.hope : current.hope, shadow: typeof template.shadow === "number" ? template.shadow : current.shadow })); toast.success(`Arquétipo ${title} aplicado ao companheiro.`); };
  const isSaving = createCharacter.isPending || updateCharacter.isPending;
  const isLoadingArchive = loadingCharacters || loadingCampaigns;
  const archiveError = charactersError || campaignsError;

  return <div className="min-h-screen bg-[#101211] text-[#eae3d5]"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><header className="border-b border-white/10 pb-7"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#83a89a]">O Um Anel · 2ª edição · ficha 09</p><div className="mt-3 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h1 className="font-serif text-5xl leading-none tracking-[-0.04em] text-[#f4eee4]">Estrada, canção<br />e sombra.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#b8b3a8]">Registre companheiros da Terra-média, conecte-os à campanha e preserve recursos, atributos, perícias e marcas do caminho.</p></div><div className="flex flex-wrap items-center gap-2"><SheetSystemSwitcher active="o-um-anel" /><SystemRuleTooltip systemId="o-um-anel" /></div></div></header>{archiveError ? <div className="mt-5 border border-[#b55b32]/55 bg-[#3b1d19]/60 p-4 text-sm text-[#ffb09d]">Não foi possível consultar o arquivo persistente agora. Atualize a página para tentar novamente.</div> : isLoadingArchive ? <div className="mt-5 flex items-center gap-2 border border-[#83a89a]/35 bg-[#171a18] p-4 text-sm text-[#a9c7bb]"><LoaderCircle className="h-4 w-4 animate-spin" /> Consultando companheiros e campanhas preservados…</div> : null}
  <section className="mt-7 grid gap-5 xl:grid-cols-[0.72fr_1.28fr]"><aside className="border border-white/10 bg-[#171a18] p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]">Companheiros preservados</p><Button onClick={newCharacter} variant="outline" size="sm" className="rounded-none border-white/20 text-[#eae3d5]"><Plus className="mr-1 h-4 w-4" /> Nova</Button></div><div className="mt-4 grid gap-2">{fellowship.length ? fellowship.map((character) => <button key={character.id} onClick={() => openCharacter(character)} className={`border p-3 text-left ${selectedId === character.id ? "border-[#b55b32] bg-[#b55b32]/10" : "border-white/10 bg-black/10 hover:border-[#83a89a]/50"}`}><p className="font-serif text-xl text-[#f4eee4]">{character.name}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[0.13em] text-[#a9c7bb]">{character.concept || "companheiro sem chamada"}</p></button>) : <p className="text-sm leading-6 text-[#b8b3a8]">Nenhum companheiro foi registrado ainda.</p>}</div></aside>
  <main className="space-y-5"><article className="relative overflow-hidden border border-[#83a89a]/45 bg-[#171a18] p-6"><div className="absolute inset-0 dossier-grid opacity-15" /><div className="relative"><div className="grid gap-4 md:grid-cols-3"><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Nome<input value={name} onChange={(event) => setName(event.target.value)} className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Conceito<input value={concept} onChange={(event) => setConcept(event.target.value)} className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Campanha<select value={campaignId} onChange={(event) => setCampaignId(event.target.value)} className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]"><option value="">Sem vínculo</option>{oneRingCampaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.title}</option>)}</select></label></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Cultura<input value={sheet.culture} onChange={(event) => setSheet({ ...sheet, culture: event.target.value })} placeholder="Ex.: Hobbits do Condado" className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Chamado<input value={sheet.calling} onChange={(event) => setSheet({ ...sheet, calling: event.target.value })} placeholder="Ex.: Guardião" className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Caminho da Sombra<input value={sheet.shadowPath} onChange={(event) => setSheet({ ...sheet, shadowPath: event.target.value })} placeholder="Ex.: Desespero" className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label></div></div></article>
  <section className="grid gap-5 lg:grid-cols-[1fr_1.25fr]"><article className="border border-white/10 bg-[#171a18] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]"><Heart className="h-4 w-4 text-[#d27648]" /> Recursos da jornada</div><div className="mt-4 grid gap-4">{ONE_RING.resources.map((resource) => <label key={resource.id} className="flex items-center justify-between gap-3 text-sm"><span>{resource.label}</span><input type="number" min={resource.min} max={resource.max} value={sheet[resource.id as "endurance" | "hope" | "shadow"]} onChange={(event) => setSheet({ ...sheet, [resource.id]: Math.min(resource.max, Math.max(resource.min, Number(event.target.value))) })} className="h-9 w-20 border border-white/15 bg-[#101211] px-2 text-right text-[#f4eee4]" /></label>)}</div><div className="mt-5 border-t border-white/10 pt-4 text-xs leading-5 text-[#b8b3a8]">Esperança sustenta feitos heroicos; Sombra registra o peso do caminho. Ambos acompanham a ficha persistida.</div></article><article className="border border-white/10 bg-[#171a18] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]"><UserRound className="h-4 w-4 text-[#d27648]" /> Atributos</div><div className="mt-4 grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">{ONE_RING.attributes.map((trait) => <div key={trait.id} className="border-b border-white/10 pb-3 transition-colors hover:border-[#83a89a]/60"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-[#83a89a]">{trait.group}</p><div className="mt-2 flex items-center justify-between gap-2"><span className="flex items-center gap-1 text-sm">{trait.label}<AttributeRuleTooltip systemId="o-um-anel" attribute={trait.label} /></span><span className="flex items-center gap-2"><button type="button" aria-label={`Rolar ${trait.label}`} onClick={() => rollTrait({ id: `attribute:${trait.id}`, label: trait.label, detail: "Atributo" })} className="text-[#d27648] hover:text-[#ffb08e]"><Dice6 className="h-3.5 w-3.5" /></button><button aria-label={`Reduzir ${trait.label}`} onClick={() => changeTrait("attributes", trait.id, -1, trait.min, trait.max)} className="text-[#a9c7bb]"><ChevronDown className="h-4 w-4" /></button><strong>{sheet.attributes[trait.id]}</strong><button aria-label={`Aumentar ${trait.label}`} onClick={() => changeTrait("attributes", trait.id, 1, trait.min, trait.max)} className="text-[#d27648]"><ChevronUp className="h-4 w-4" /></button></span></div></div>)}</div></article></section>
  <article className="border border-white/10 bg-[#171a18] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]"><Sparkles className="h-4 w-4 text-[#d27648]" /> Perícias de aventura</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{ONE_RING.skills.map((trait) => <div key={trait.id} className="flex items-center justify-between border-b border-white/10 py-2 text-sm"><span>{trait.label}</span><span className="flex items-center gap-2"><button type="button" aria-label={`Rolar ${trait.label}`} onClick={() => rollTrait({ id: `skill:${trait.id}`, label: trait.label, detail: "Perícia" })} className="text-[#d27648] hover:text-[#ffb08e]"><Dice6 className="h-3.5 w-3.5" /></button><button onClick={() => changeTrait("skills", trait.id, -1, trait.min, trait.max)} className="text-[#a9c7bb]"><ChevronDown className="h-4 w-4" /></button><strong>{sheet.skills[trait.id]}</strong><button onClick={() => changeTrait("skills", trait.id, 1, trait.min, trait.max)} className="text-[#d27648]"><ChevronUp className="h-4 w-4" /></button></span></div>)}</div></article>
  <article className="archive-paper border border-[#161715]/20 p-5 text-[#161715]"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#b55b32]"><Moon className="h-4 w-4" /> Registro da companhia</div><textarea value={sheet.notes} onChange={(event) => setSheet({ ...sheet, notes: event.target.value })} placeholder="Jornadas, vínculos, tesouros e presságios que a companhia não deve esquecer." className="mt-4 min-h-28 w-full border border-[#161715]/20 bg-[#fffaf0] p-3 text-sm leading-6 outline-none focus:border-[#b55b32]" /></article>
  <TemporaryModifiersPanel modifiers={sheet.temporaryModifiers} onChange={(temporaryModifiers) => setSheet({ ...sheet, temporaryModifiers })} />
  <article className="border border-[#83a89a]/35 bg-[#171a18] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]">Rolagens por traço</p><p className="mt-2 text-xs leading-5 text-[#b8b3a8]">Clique em um atributo ou perícia para rolar com as condições temporárias aplicáveis.</p><div className="mt-4 grid max-h-56 gap-2 overflow-y-auto pr-1 sm:grid-cols-2 xl:grid-cols-3">{directRollOptions.map((option) => <button key={option.id} type="button" onClick={() => rollTrait(option)} className="flex items-center justify-between border border-white/10 bg-black/10 px-3 py-2 text-left text-sm text-[#f4eee4] hover:border-[#d27648] hover:bg-[#d27648]/10"><span>{option.label}</span><Sparkles className="h-4 w-4 text-[#d27648]" /></button>)}</div></article>
  <SheetCreationGuide system="O Um Anel" intro="Comece pela história do companheiro. Os valores sugeridos são um ponto de partida; a mesa decide os detalhes da cultura e da jornada." steps={["Defina nome, cultura, chamado e o caminho que a Sombra pode revelar.", "Distribua atributos, escolha perícias que expressem a história e ajuste Vigor, Esperança e Sombra.", "Vincule o companheiro à campanha, registre suas jornadas e preserve a ficha no arquivo."]} />
  <div className="flex flex-wrap justify-end gap-2"><DiceStyleControl diceStyle={diceStyle} setDiceStyle={setDiceStyle} /><DiceSoundControl enabled={diceSoundEnabled} setEnabled={setDiceSoundEnabled} volume={diceSoundVolume} setVolume={setDiceSoundVolume} /><DiceRollHistorySheet characterId={selectedId} characterName={name} /><CharacterShareLinkButton characterId={selectedId} /></div>
  <CustomArchetypePanel systemId="o-um-anel" snapshot={{ culture: sheet.culture, calling: sheet.calling, shadowPath: sheet.shadowPath, attributes: sheet.attributes, skills: sheet.skills, endurance: sheet.endurance, hope: sheet.hope, shadow: sheet.shadow }} onApply={applyCustomArchetype} />
  <QuickRollPanel title="Rolagens rápidas da jornada" intro="Role o dado de feito d12 e os dados de perícia d6. O alvo usa o atributo da ficha; resultados são registrados quando há um companheiro preservado aberto." options={[{ id: "travessia", label: "Travessia", detail: "Força + Viagem" }, { id: "vigia", label: "Vigia", detail: "Espírito + Percepção" }, { id: "cacada", label: "Caçada", detail: "Força + Caçada" }, { id: "canção", label: "Canção", detail: "Coração + Canção" }, { id: "presenca", label: "Presença", detail: "Coração + Presença" }]} onRoll={performQuickRoll} />
  {rollingQuickRoll ? <DiceRollInProgress {...rollingQuickRoll} diceStyle={diceStyle} /> : null}
  {quickRollResult ? <DiceRollFeedback dice={[quickRollResult.featDie, ...quickRollResult.skillDice]} modifier={quickRollResult.modifier} diceStyle={diceStyle}><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">{quickRollResult.label} · alvo {quickRollResult.target} · {quickRollResult.successes} sucesso(s)</p><p className="mt-2 font-mono text-xs tracking-[0.16em] text-[#f4eee4]">Dado de feito {quickRollResult.featDie} · perícia {quickRollResult.skillDice.length ? quickRollResult.skillDice.join(" · ") : "—"}</p></DiceRollFeedback> : null}
  <div className="flex flex-col justify-between gap-3 border-t border-white/10 pt-6 sm:flex-row sm:items-center"><p className={`flex items-center gap-2 text-xs ${isSaving ? "text-[#a9c7bb]" : lastSavedAt ? "text-[#9dccb8]" : "text-[#b8b3a8]"}`}>{isSaving ? <><LoaderCircle className="h-4 w-4 animate-spin" /> Gravando alterações no arquivo…</> : lastSavedAt ? <><CheckCircle2 className="h-4 w-4" /> Salvo com sucesso às {lastSavedAt.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}.</> : "As alterações serão preservadas quando você salvar."}</p><Button onClick={save} disabled={isSaving} className="h-12 rounded-none bg-[#b55b32] px-6 text-[10px] font-bold uppercase tracking-[0.16em] text-[#161715] hover:bg-[#d27648]">{isSaving ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />} {isSaving ? "Salvando" : selectedId ? "Salvar companheiro" : "Preservar companheiro"}</Button></div></main></section></div></div>;
}

export default function OneRingSheet() { return <DashboardLayout><OneRingSheetContent /></DashboardLayout>; }
