import DashboardLayout from "@/components/DashboardLayout";
import { SystemRuleTooltip } from "@/components/SystemRuleTooltip";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { getRpgSystem } from "@shared/rpg-systems";
import { BookOpen, ChevronDown, ChevronUp, Heart, Moon, Plus, Save, Sparkles, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const ONE_RING = getRpgSystem("o-um-anel")!;
type OneRingSheetData = { culture: string; calling: string; shadowPath: string; attributes: Record<string, number>; skills: Record<string, number>; endurance: number; hope: number; shadow: number; notes: string };

function createOneRingSheetData(): OneRingSheetData {
  return { culture: "", calling: "", shadowPath: "", attributes: { strength: 2, heart: 2, wits: 2 }, skills: Object.fromEntries(ONE_RING.skills.map((skill) => [skill.id, 0])), endurance: 24, hope: 8, shadow: 0, notes: "" };
}

function hydrateSheet(value: unknown): OneRingSheetData {
  const base = createOneRingSheetData();
  const raw = (value || {}) as Partial<OneRingSheetData>;
  return { ...base, ...raw, attributes: { ...base.attributes, ...(raw.attributes || {}) }, skills: { ...base.skills, ...(raw.skills || {}) } };
}

function OneRingSheetContent() {
  const utils = trpc.useUtils();
  const { data: characters = [], isLoading: loadingCharacters, error: charactersError } = trpc.characters.mine.useQuery();
  const { data: campaigns = [], isLoading: loadingCampaigns, error: campaignsError } = trpc.campaigns.mine.useQuery();
  const fellowship = useMemo(() => characters.filter((character) => character.systemId === "o-um-anel"), [characters]);
  const oneRingCampaigns = useMemo(() => campaigns.filter((campaign) => campaign.systemId === "o-um-anel"), [campaigns]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [name, setName] = useState("");
  const [concept, setConcept] = useState("");
  const [campaignId, setCampaignId] = useState("");
  const [sheet, setSheet] = useState<OneRingSheetData>(() => createOneRingSheetData());
  const createCharacter = trpc.characters.create.useMutation({ onSuccess: async (created) => { await utils.characters.mine.invalidate(); setSelectedId(created.id); toast.success("Ficha de O Um Anel preservada no arquivo."); }, onError: (error) => toast.error(error.message) });
  const updateCharacter = trpc.characters.update.useMutation({ onSuccess: async () => { await utils.characters.mine.invalidate(); toast.success("Ficha de O Um Anel atualizada."); }, onError: (error) => toast.error(error.message) });
  const openCharacter = (character: typeof fellowship[number]) => { setSelectedId(character.id); setName(character.name); setConcept(character.concept || ""); setCampaignId(character.campaignId ? String(character.campaignId) : ""); setSheet(hydrateSheet(character.sheetData)); };
  const newCharacter = () => { setSelectedId(null); setName(""); setConcept(""); setCampaignId(""); setSheet(createOneRingSheetData()); };
  const changeTrait = (group: "attributes" | "skills", id: string, delta: number, min: number, max: number) => setSheet((current) => ({ ...current, [group]: { ...current[group], [id]: Math.min(max, Math.max(min, (current[group][id] ?? min) + delta)) } }));
  const save = () => { if (name.trim().length < 2) { toast.error("Informe o nome do companheiro."); return; } const input = { name: name.trim(), concept: concept.trim() || undefined, campaignId: campaignId ? Number(campaignId) : null, sheetData: sheet }; if (selectedId) updateCharacter.mutate({ ...input, characterId: selectedId }); else createCharacter.mutate({ ...input, systemId: "o-um-anel" }); };
  const isSaving = createCharacter.isPending || updateCharacter.isPending;
  const isLoadingArchive = loadingCharacters || loadingCampaigns;
  const archiveError = charactersError || campaignsError;

  return <div className="min-h-screen bg-[#101211] text-[#eae3d5]"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><header className="border-b border-white/10 pb-7"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#83a89a]">O Um Anel · 2ª edição · ficha 09</p><div className="mt-3 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h1 className="font-serif text-5xl leading-none tracking-[-0.04em] text-[#f4eee4]">Estrada, canção<br />e sombra.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#b8b3a8]">Registre companheiros da Terra-média, conecte-os à campanha e preserve recursos, atributos, perícias e marcas do caminho.</p></div><SystemRuleTooltip systemId="o-um-anel" /></div></header>{archiveError ? <div className="mt-5 border border-[#b55b32]/55 bg-[#3b1d19]/60 p-4 text-sm text-[#ffb09d]">Não foi possível consultar o arquivo persistente agora. Atualize a página para tentar novamente.</div> : isLoadingArchive ? <div className="mt-5 border border-[#83a89a]/35 bg-[#171a18] p-4 text-sm text-[#a9c7bb]">Consultando companheiros e campanhas preservados…</div> : null}
  <section className="mt-7 grid gap-5 xl:grid-cols-[0.72fr_1.28fr]"><aside className="border border-white/10 bg-[#171a18] p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]">Companheiros preservados</p><Button onClick={newCharacter} variant="outline" size="sm" className="rounded-none border-white/20 text-[#eae3d5]"><Plus className="mr-1 h-4 w-4" /> Nova</Button></div><div className="mt-4 grid gap-2">{fellowship.length ? fellowship.map((character) => <button key={character.id} onClick={() => openCharacter(character)} className={`border p-3 text-left ${selectedId === character.id ? "border-[#b55b32] bg-[#b55b32]/10" : "border-white/10 bg-black/10 hover:border-[#83a89a]/50"}`}><p className="font-serif text-xl text-[#f4eee4]">{character.name}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[0.13em] text-[#a9c7bb]">{character.concept || "companheiro sem chamada"}</p></button>) : <p className="text-sm leading-6 text-[#b8b3a8]">Nenhum companheiro foi registrado ainda.</p>}</div></aside>
  <main className="space-y-5"><article className="relative overflow-hidden border border-[#83a89a]/45 bg-[#171a18] p-6"><div className="absolute inset-0 dossier-grid opacity-15" /><div className="relative"><div className="grid gap-4 md:grid-cols-3"><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Nome<input value={name} onChange={(event) => setName(event.target.value)} className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Conceito<input value={concept} onChange={(event) => setConcept(event.target.value)} className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Campanha<select value={campaignId} onChange={(event) => setCampaignId(event.target.value)} className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]"><option value="">Sem vínculo</option>{oneRingCampaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.title}</option>)}</select></label></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Cultura<input value={sheet.culture} onChange={(event) => setSheet({ ...sheet, culture: event.target.value })} placeholder="Ex.: Hobbits do Condado" className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Chamado<input value={sheet.calling} onChange={(event) => setSheet({ ...sheet, calling: event.target.value })} placeholder="Ex.: Guardião" className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Caminho da Sombra<input value={sheet.shadowPath} onChange={(event) => setSheet({ ...sheet, shadowPath: event.target.value })} placeholder="Ex.: Desespero" className="h-10 border border-white/15 bg-[#101211] px-3 text-sm normal-case tracking-normal text-[#eae3d5]" /></label></div></div></article>
  <section className="grid gap-5 lg:grid-cols-[1fr_1.25fr]"><article className="border border-white/10 bg-[#171a18] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]"><Heart className="h-4 w-4 text-[#d27648]" /> Recursos da jornada</div><div className="mt-4 grid gap-4">{ONE_RING.resources.map((resource) => <label key={resource.id} className="flex items-center justify-between gap-3 text-sm"><span>{resource.label}</span><input type="number" min={resource.min} max={resource.max} value={sheet[resource.id as "endurance" | "hope" | "shadow"]} onChange={(event) => setSheet({ ...sheet, [resource.id]: Math.min(resource.max, Math.max(resource.min, Number(event.target.value))) })} className="h-9 w-20 border border-white/15 bg-[#101211] px-2 text-right text-[#f4eee4]" /></label>)}</div><div className="mt-5 border-t border-white/10 pt-4 text-xs leading-5 text-[#b8b3a8]">Esperança sustenta feitos heroicos; Sombra registra o peso do caminho. Ambos acompanham a ficha persistida.</div></article><article className="border border-white/10 bg-[#171a18] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]"><UserRound className="h-4 w-4 text-[#d27648]" /> Atributos</div><div className="mt-4 grid gap-4 md:grid-cols-3">{ONE_RING.attributes.map((trait) => <div key={trait.id} className="border-b border-white/10 pb-3"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-[#83a89a]">{trait.group}</p><div className="mt-2 flex items-center justify-between gap-2"><span className="text-sm">{trait.label}</span><span className="flex items-center gap-2"><button onClick={() => changeTrait("attributes", trait.id, -1, trait.min, trait.max)} className="text-[#a9c7bb]"><ChevronDown className="h-4 w-4" /></button><strong>{sheet.attributes[trait.id]}</strong><button onClick={() => changeTrait("attributes", trait.id, 1, trait.min, trait.max)} className="text-[#d27648]"><ChevronUp className="h-4 w-4" /></button></span></div></div>)}</div></article></section>
  <article className="border border-white/10 bg-[#171a18] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]"><Sparkles className="h-4 w-4 text-[#d27648]" /> Perícias de aventura</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{ONE_RING.skills.map((trait) => <div key={trait.id} className="flex items-center justify-between border-b border-white/10 py-2 text-sm"><span>{trait.label}</span><span className="flex items-center gap-2"><button onClick={() => changeTrait("skills", trait.id, -1, trait.min, trait.max)} className="text-[#a9c7bb]"><ChevronDown className="h-4 w-4" /></button><strong>{sheet.skills[trait.id]}</strong><button onClick={() => changeTrait("skills", trait.id, 1, trait.min, trait.max)} className="text-[#d27648]"><ChevronUp className="h-4 w-4" /></button></span></div>)}</div></article>
  <article className="archive-paper border border-[#161715]/20 p-5 text-[#161715]"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#b55b32]"><Moon className="h-4 w-4" /> Registro da companhia</div><textarea value={sheet.notes} onChange={(event) => setSheet({ ...sheet, notes: event.target.value })} placeholder="Jornadas, vínculos, tesouros e presságios que a companhia não deve esquecer." className="mt-4 min-h-28 w-full border border-[#161715]/20 bg-[#fffaf0] p-3 text-sm leading-6 outline-none focus:border-[#b55b32]" /></article>
  <div className="flex justify-end border-t border-white/10 pt-6"><Button onClick={save} disabled={isSaving} className="h-12 rounded-none bg-[#b55b32] px-6 text-[10px] font-bold uppercase tracking-[0.16em] text-[#161715] hover:bg-[#d27648]"><Save className="mr-2 h-4 w-4" /> {selectedId ? "Salvar companheiro" : "Preservar companheiro"}</Button></div></main></section></div></div>;
}

export default function OneRingSheet() { return <DashboardLayout><OneRingSheetContent /></DashboardLayout>; }
