import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { downloadJsonFile, parseCharacterSharePayload, createCharacterJsonEnvelope, slugifyFilename } from "@/lib/sheetJson";
import { Download, FileWarning, Share2 } from "lucide-react";
import React, { useMemo } from "react";

export default function SharedJsonCharacterSheet() {
  const encoded = useMemo(() => new URLSearchParams(typeof window === "undefined" ? "" : window.location.search).get("payload") || "", []);
  const parsed = useMemo(() => parseCharacterSharePayload(encoded), [encoded]);
  const exportFile = () => { if (!parsed) return; downloadJsonFile(createCharacterJsonEnvelope(parsed), `${slugifyFilename(parsed.name)}-compartilhada.json`); };

  return <DashboardLayout><main className="min-h-screen bg-[#101211] px-5 py-10 text-[#eae3d5] sm:px-8"><div className="mx-auto max-w-3xl">{parsed ? <article className="border border-[#83a89a]/45 bg-[#171a18] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-white/10 pb-6"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#83a89a]"><Share2 className="h-4 w-4 text-[#d27648]" /> Ficha compartilhada · leitura</p><h1 className="mt-3 font-serif text-5xl text-[#f4eee4]">{parsed.name}</h1><p className="mt-2 text-sm text-[#b8b3a8]">{parsed.concept || "Conceito não informado"} · {parsed.systemId}</p></div><Button type="button" onClick={exportFile} variant="outline" className="h-10 rounded-none border-[#83a89a]/45 text-[10px] font-bold uppercase tracking-[.12em] text-[#eae3d5]"><Download className="mr-2 h-4 w-4" /> Baixar JSON</Button></div><dl className="mt-6 grid gap-3 sm:grid-cols-3"><div className="border border-white/10 bg-black/10 p-4"><dt className="text-[9px] font-bold uppercase tracking-[.12em] text-[#8f958c]">Sistema</dt><dd className="mt-2 text-sm text-[#f4eee4]">{parsed.systemId}</dd></div><div className="border border-white/10 bg-black/10 p-4"><dt className="text-[9px] font-bold uppercase tracking-[.12em] text-[#8f958c]">Nível</dt><dd className="mt-2 text-sm text-[#f4eee4]">{parsed.level ? `Nível ${parsed.level}` : "Não definido"}</dd></div><div className="border border-white/10 bg-black/10 p-4"><dt className="text-[9px] font-bold uppercase tracking-[.12em] text-[#8f958c]">Tags</dt><dd className="mt-2 flex flex-wrap gap-1 text-sm text-[#a9c7bb]">{parsed.tags?.length ? parsed.tags.map((tag) => <span key={tag}>#{tag}</span>) : "Nenhuma"}</dd></div></dl><p className="mt-6 border-l-2 border-[#b55b32] pl-3 text-xs leading-5 text-[#b8b3a8]">Este link contém uma cópia codificada da ficha. Para preservar os dados, baixe o JSON e importe-o no Cofre Local.</p></article> : <article className="border border-[#b55b32]/60 bg-[#171a18] p-8 text-center"><FileWarning className="mx-auto h-10 w-10 text-[#d27648]" /><h1 className="mt-4 font-serif text-4xl text-[#f4eee4]">Link de ficha inválido</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#b8b3a8]">O payload está ausente, corrompido ou excede o tamanho permitido. Peça ao remetente um novo link ou use o arquivo JSON exportado.</p></article>}</div></main></DashboardLayout>;
}
