import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { mapCoordinatePercent, normalizedMapCoordinate } from "@shared/map-tabletop";
import { Crosshair, Grip, ImageUp, MapPinned, Minus, Move, Pencil, Plus, RotateCcw, Save, Sparkles, Trash2 } from "lucide-react";
import React, { PointerEvent, WheelEvent, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";

type CampaignOption = { id: number; title: string; memberRole?: "narrator" | "player" | "observer" | null };
type MarkerType = "location" | "character" | "threat" | "objective" | "secret";
type Point = { x: number; y: number };
type MarkerDraft = { label: string; description: string; markerType: MarkerType; color: string };
type EditableMarker = { id: number; label: string; description: string | null; markerType: MarkerType; color: string };

const markerLabels: Record<MarkerType, string> = { location: "Local", character: "Personagem", threat: "Ameaça", objective: "Objetivo", secret: "Segredo" };
const markerColors = ["#b55b32", "#83a89a", "#d6b15d", "#a16b8d", "#7397b5"];
const imageProviderLabels = { openai: "OpenAI", gemini: "Gemini" } as const;
const blankMarker = (): MarkerDraft => ({ label: "", description: "", markerType: "location", color: markerColors[0] });

function asDataUrl(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("Não foi possível ler a imagem."));
    reader.onload = () => typeof reader.result === "string" ? resolve(reader.result) : reject(new Error("Arquivo de mapa inválido."));
    reader.readAsDataURL(file);
  });
}

function coordinateAtPoint(event: PointerEvent<HTMLDivElement>, stage: HTMLDivElement | null): Point | null {
  if (!stage) return null;
  const rect = stage.getBoundingClientRect();
  if (!rect.width || !rect.height) return null;
  return { x: normalizedMapCoordinate((event.clientX - rect.left) / rect.width), y: normalizedMapCoordinate((event.clientY - rect.top) / rect.height) };
}

function ColorChoices({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <div className="mt-3 flex gap-2" aria-label="Cor do marcador">{markerColors.map((color) => <button key={color} type="button" onClick={() => onChange(color)} aria-label={`Selecionar cor ${color}`} className={`h-6 w-6 rounded-full border-2 ${value === color ? "border-[#f4eee4]" : "border-transparent"}`} style={{ backgroundColor: color }} />)}</div>;
}

function MarkerFields({ draft, setDraft, prefix }: { draft: MarkerDraft; setDraft: (next: MarkerDraft) => void; prefix: string }) {
  return <><Label htmlFor={`${prefix}-label`} className="mt-4 block text-[9px] font-bold uppercase tracking-[0.13em] text-[#a9c7bb]">Identificação</Label><Input id={`${prefix}-label`} value={draft.label} onChange={(event) => setDraft({ ...draft, label: event.target.value })} placeholder="Ex.: Vigia do portão" className="mt-2 h-10 rounded-none border-white/15 bg-[#101211] text-[#eae3d5] placeholder:text-[#6f746c]" /><Label htmlFor={`${prefix}-type`} className="mt-3 block text-[9px] font-bold uppercase tracking-[0.13em] text-[#a9c7bb]">Tipo</Label><select id={`${prefix}-type`} value={draft.markerType} onChange={(event) => setDraft({ ...draft, markerType: event.target.value as MarkerType })} className="mt-2 h-10 w-full border border-white/15 bg-[#101211] px-3 text-sm text-[#eae3d5] outline-none focus:border-[#b55b32]">{Object.entries(markerLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Label htmlFor={`${prefix}-description`} className="mt-3 block text-[9px] font-bold uppercase tracking-[0.13em] text-[#a9c7bb]">Nota opcional</Label><Textarea id={`${prefix}-description`} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} className="mt-2 min-h-20 rounded-none border-white/15 bg-[#101211] text-sm text-[#eae3d5]" /><ColorChoices value={draft.color} onChange={(color) => setDraft({ ...draft, color })} /></>;
}

export function CampaignMapTabletop({ campaigns, initialCampaignId }: { campaigns: CampaignOption[]; initialCampaignId: number | null }) {
  const utils = trpc.useUtils();
  const [selectedCampaignId, setSelectedCampaignId] = useState<number | null>(initialCampaignId);
  const [selectedMapId, setSelectedMapId] = useState<number | null>(null);
  const [newMapTitle, setNewMapTitle] = useState("");
  const [creativeDirection, setCreativeDirection] = useState("");
  const [aspectRatio, setAspectRatio] = useState<"16:9" | "4:3" | "1:1">("16:9");
  const [generationError, setGenerationError] = useState<string | null>(null);
  const [draftTitle, setDraftTitle] = useState("");
  const [gridEnabled, setGridEnabled] = useState(true);
  const [gridSize, setGridSize] = useState(50);
  const [scale, setScale] = useState(1);
  const [pan, setPan] = useState<Point>({ x: 0, y: 0 });
  const [panStart, setPanStart] = useState<{ clientX: number; clientY: number; origin: Point; moved: boolean } | null>(null);
  const [pendingPosition, setPendingPosition] = useState<Point | null>(null);
  const [markerDrag, setMarkerDrag] = useState<number | null>(null);
  const [markerPreview, setMarkerPreview] = useState<{ id: number; positionX: number; positionY: number } | null>(null);
  const [markerDraft, setMarkerDraft] = useState<MarkerDraft>(blankMarker);
  const [editingMarkerId, setEditingMarkerId] = useState<number | null>(null);
  const stageRef = useRef<HTMLDivElement>(null);

  const activeCampaign = campaigns.find((campaign) => campaign.id === selectedCampaignId) ?? campaigns[0] ?? null;
  const input = useMemo(() => ({ campaignId: activeCampaign?.id ?? -1 }), [activeCampaign?.id]);
  const mapsQuery = trpc.maps.list.useQuery(input, { enabled: Boolean(activeCampaign) });
  const maps = mapsQuery.data ?? [];
  const selectedMap = maps.find((map) => map.id === selectedMapId) ?? maps[0] ?? null;
  const isNarrator = activeCampaign?.memberRole === "narrator";

  useEffect(() => { if (activeCampaign && activeCampaign.id !== selectedCampaignId) setSelectedCampaignId(activeCampaign.id); }, [activeCampaign, selectedCampaignId]);
  useEffect(() => { setSelectedMapId((current) => maps.some((map) => map.id === current) ? current : maps[0]?.id ?? null); }, [maps]);
  useEffect(() => {
    if (!selectedMap) return;
    setDraftTitle(selectedMap.title); setGridEnabled(Boolean(selectedMap.gridEnabled)); setGridSize(selectedMap.gridSize);
    setPendingPosition(null); setEditingMarkerId(null); setMarkerPreview(null); setScale(1); setPan({ x: 0, y: 0 });
  }, [selectedMap?.id]);

  const refresh = async () => { if (activeCampaign) await utils.maps.list.invalidate({ campaignId: activeCampaign.id }); };
  const createMap = trpc.maps.create.useMutation({ onSuccess: async (map) => { await refresh(); setSelectedMapId(map?.id ?? null); setNewMapTitle(""); toast.success("Mapa criado no arquivo da campanha."); }, onError: (error) => toast.error(error.message) });
  const updateMap = trpc.maps.update.useMutation({ onSuccess: async () => { await refresh(); toast.success("Configuração da mesa preservada."); }, onError: (error) => toast.error(error.message) });
  const uploadImage = trpc.maps.uploadImage.useMutation({ onSuccess: async () => { await refresh(); toast.success("Imagem tática enviada ao arquivo."); }, onError: (error) => toast.error(error.message) });
  const generateImage = trpc.maps.generateImage.useMutation({ onSuccess: async (map) => { setGenerationError(null); await refresh(); const provider = map?.imageProvider === "gemini" ? "Gemini (contingência)" : "OpenAI"; toast.success(`Mapa procedural gerado e preservado via ${provider}.`); }, onError: (error) => { setGenerationError(error.message); toast.error(error.message); } });
  const createMarker = trpc.maps.createMarker.useMutation({ onSuccess: async () => { await refresh(); setPendingPosition(null); setMarkerDraft(blankMarker()); toast.success("Marcador posicionado na mesa."); }, onError: (error) => toast.error(error.message) });
  const updateMarker = trpc.maps.updateMarker.useMutation({ onSuccess: async () => { await refresh(); setEditingMarkerId(null); toast.success("Marcador atualizado."); }, onError: (error) => toast.error(error.message) });
  const moveMarker = trpc.maps.moveMarker.useMutation({ onSuccess: refresh, onError: (error) => toast.error(error.message) });
  const removeMarker = trpc.maps.removeMarker.useMutation({ onSuccess: async () => { await refresh(); setEditingMarkerId(null); toast.success("Marcador removido."); }, onError: (error) => toast.error(error.message) });

  const addMap = () => { if (!activeCampaign) return; const title = newMapTitle.trim(); if (title.length < 3) return toast.error("Dê ao mapa um título de pelo menos três caracteres."); createMap.mutate({ campaignId: activeCampaign.id, title }); };
  const saveMap = () => { if (!activeCampaign || !selectedMap) return; const title = draftTitle.trim(); if (title.length < 3) return toast.error("Dê ao mapa um título de pelo menos três caracteres."); updateMap.mutate({ campaignId: activeCampaign.id, mapId: selectedMap.id, title, gridEnabled, gridSize }); };
  const chooseImage = async (file?: File) => {
    if (!file || !activeCampaign || !selectedMap) return;
    if (!["image/png", "image/jpeg", "image/webp"].includes(file.type)) return toast.error("Use uma imagem PNG, JPEG ou WebP.");
    if (file.size > 4 * 1024 * 1024) return toast.error("A imagem deve ter no máximo 4 MB.");
    try { uploadImage.mutate({ campaignId: activeCampaign.id, mapId: selectedMap.id, imageData: await asDataUrl(file) }); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível ler a imagem."); }
  };
  const createProceduralImage = () => { if (!activeCampaign || !selectedMap || creativeDirection.trim().length < 12) return toast.error("Descreva o terreno em ao menos doze caracteres."); setGenerationError(null); generateImage.mutate({ campaignId: activeCampaign.id, mapId: selectedMap.id, creativeDirection: creativeDirection.trim(), aspectRatio }); };
  const submitNewMarker = () => { if (!activeCampaign || !selectedMap || !pendingPosition) return; const label = markerDraft.label.trim(); if (!label) return toast.error("Nomeie o marcador antes de posicioná-lo."); createMarker.mutate({ campaignId: activeCampaign.id, mapId: selectedMap.id, label, description: markerDraft.description.trim() || undefined, markerType: markerDraft.markerType, color: markerDraft.color, positionX: pendingPosition.x, positionY: pendingPosition.y }); };
  const beginMarkerEdit = (marker: EditableMarker) => { setPendingPosition(null); setEditingMarkerId(marker.id); setMarkerDraft({ label: marker.label, description: marker.description || "", markerType: marker.markerType, color: marker.color }); };
  const saveMarker = () => { if (!activeCampaign || !selectedMap || !editingMarkerId) return; const label = markerDraft.label.trim(); if (!label) return toast.error("Nomeie o marcador antes de salvá-lo."); updateMarker.mutate({ campaignId: activeCampaign.id, mapId: selectedMap.id, markerId: editingMarkerId, label, description: markerDraft.description.trim() || undefined, markerType: markerDraft.markerType, color: markerDraft.color }); };
  const zoomBy = (increment: number) => setScale((value) => Math.min(2.5, Math.max(0.5, Number((value + increment).toFixed(2)))));
  const beginPan = (event: PointerEvent<HTMLDivElement>) => { if (markerDrag !== null || event.button !== 0) return; setPanStart({ clientX: event.clientX, clientY: event.clientY, origin: pan, moved: false }); event.currentTarget.setPointerCapture(event.pointerId); };
  const movePointer = (event: PointerEvent<HTMLDivElement>) => { if (markerDrag !== null) { const point = coordinateAtPoint(event, stageRef.current); if (point) setMarkerPreview({ id: markerDrag, positionX: point.x, positionY: point.y }); return; } if (!panStart) return; const dx = event.clientX - panStart.clientX; const dy = event.clientY - panStart.clientY; if (Math.abs(dx) > 4 || Math.abs(dy) > 4) setPanStart({ ...panStart, moved: true }); setPan({ x: panStart.origin.x + dx, y: panStart.origin.y + dy }); };
  const endPointer = (event: PointerEvent<HTMLDivElement>) => { if (markerDrag !== null && selectedMap && activeCampaign) { const point = coordinateAtPoint(event, stageRef.current); if (point) moveMarker.mutate({ campaignId: activeCampaign.id, mapId: selectedMap.id, markerId: markerDrag, positionX: point.x, positionY: point.y }); setMarkerDrag(null); setMarkerPreview(null); return; } if (panStart && !panStart.moved && isNarrator) { const point = coordinateAtPoint(event, stageRef.current); if (point) { setPendingPosition(point); setEditingMarkerId(null); setMarkerDraft(blankMarker()); } } setPanStart(null); };

  return <section className="mt-8 border border-[#b55b32]/45 bg-[#171a18] p-5 sm:p-6">
    <header className="flex flex-col justify-between gap-4 border-b border-white/10 pb-5 lg:flex-row lg:items-end"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-[#a9c7bb]"><MapPinned className="h-4 w-4 text-[#d27648]" /> Mesa virtual · mapas táticos</p><h2 className="mt-3 font-serif text-4xl leading-none text-[#f4eee4]">Terreno sob vigília.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#b8b3a8]">Imagens, grade e marcadores ficam associados à campanha. Apenas narradores alteram a mesa; integrantes podem consultá-la.</p></div><label className="flex flex-col gap-2 text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Campanha de mesa<select value={activeCampaign?.id ?? ""} onChange={(event) => setSelectedCampaignId(Number(event.target.value))} className="h-10 min-w-52 border border-white/15 bg-[#101211] px-3 text-sm font-medium normal-case tracking-normal text-[#eae3d5] outline-none focus:border-[#b55b32]"><option value="" disabled>Selecione uma campanha</option>{campaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.title}</option>)}</select></label></header>
    {!activeCampaign ? <p className="mt-5 border border-dashed border-white/15 p-5 text-sm leading-6 text-[#b8b3a8]">Registre ou carregue uma campanha no Santuário para preparar a primeira mesa virtual.</p> : null}
    {activeCampaign && mapsQuery.isLoading ? <p className="mt-5 text-sm text-[#b8b3a8]">Abrindo o arquivo cartográfico…</p> : null}
    {activeCampaign && mapsQuery.error ? <div role="alert" className="mt-5 flex flex-wrap items-center justify-between gap-3 border border-[#b55b32]/60 bg-[#3b1d19]/55 p-4 text-sm text-[#ffb09d]"><span>Não foi possível consultar os mapas da campanha. {mapsQuery.error.message}</span><Button variant="outline" onClick={() => mapsQuery.refetch()} className="h-9 rounded-none border-[#ffb08e]/55 text-[9px] uppercase tracking-[0.13em] text-[#ffded1]">Tentar novamente</Button></div> : null}
    {activeCampaign && !mapsQuery.isLoading && !mapsQuery.error && !selectedMap ? <div className="mt-5 grid gap-4 border border-dashed border-white/15 p-5 md:grid-cols-[1fr_auto] md:items-end"><div><Label htmlFor="new-map-title" className="text-[9px] font-bold uppercase tracking-[0.14em] text-[#a9c7bb]">Primeiro mapa da campanha</Label><Input id="new-map-title" value={newMapTitle} onChange={(event) => setNewMapTitle(event.target.value)} placeholder="Ex.: Ruínas sob a chuva" className="mt-2 h-11 rounded-none border-white/15 bg-[#101211] text-[#eae3d5] placeholder:text-[#6f746c]" disabled={!isNarrator} /></div>{isNarrator ? <Button onClick={addMap} disabled={createMap.isPending} className="h-11 rounded-none bg-[#b55b32] text-[10px] font-bold uppercase tracking-[0.14em] text-[#101211] hover:bg-[#d27648]"><Plus className="mr-2 h-4 w-4" />{createMap.isPending ? "Criando" : "Criar mapa"}</Button> : <p className="text-sm leading-6 text-[#b8b3a8]">Somente o narrador pode abrir uma mesa nova.</p>}</div> : null}
    {selectedMap ? <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_19rem]"><div className="min-w-0"><div className="flex flex-col gap-3 border border-white/10 bg-[#101211] px-3 py-2 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-2"><Grip className="h-4 w-4 shrink-0 text-[#83a89a]" /><select value={selectedMap.id} onChange={(event) => setSelectedMapId(Number(event.target.value))} className="min-w-0 bg-transparent text-sm font-semibold text-[#f4eee4] outline-none">{maps.map((map) => <option key={map.id} value={map.id} className="bg-[#101211]">{map.title}</option>)}</select></div><div className="flex items-center gap-1"><Button variant="outline" size="icon" onClick={() => zoomBy(-0.1)} aria-label="Diminuir zoom" className="h-8 w-8 rounded-none border-white/15 text-[#eae3d5]"><Minus className="h-3.5 w-3.5" /></Button><span className="w-12 text-center text-[10px] font-bold tabular-nums text-[#a9c7bb]">{Math.round(scale * 100)}%</span><Button variant="outline" size="icon" onClick={() => zoomBy(0.1)} aria-label="Aumentar zoom" className="h-8 w-8 rounded-none border-white/15 text-[#eae3d5]"><Plus className="h-3.5 w-3.5" /></Button><Button variant="outline" size="icon" onClick={() => { setScale(1); setPan({ x: 0, y: 0 }); }} aria-label="Redefinir visualização" className="ml-1 h-8 w-8 rounded-none border-white/15 text-[#eae3d5]"><RotateCcw className="h-3.5 w-3.5" /></Button></div></div>{isNarrator ? <div className="mt-3 flex flex-col gap-2 border border-white/10 bg-[#101211] p-3 sm:flex-row"><Input aria-label="Novo mapa de campanha" value={newMapTitle} onChange={(event) => setNewMapTitle(event.target.value)} placeholder="Novo mapa da campanha" className="h-9 rounded-none border-white/15 bg-[#171a18] text-sm text-[#eae3d5] placeholder:text-[#6f746c]" /><Button onClick={addMap} disabled={createMap.isPending} className="h-9 shrink-0 rounded-none bg-[#b55b32] px-3 text-[9px] font-bold uppercase tracking-[0.12em] text-[#101211] hover:bg-[#d27648]"><Plus className="mr-1.5 h-3.5 w-3.5" />{createMap.isPending ? "Criando" : "Adicionar mapa"}</Button></div> : null}
      <div className="relative mt-3 aspect-video touch-none overflow-hidden border border-[#b55b32]/45 bg-[#0b0d0c]" onWheel={(event: WheelEvent<HTMLDivElement>) => { event.preventDefault(); zoomBy(event.deltaY < 0 ? 0.1 : -0.1); }} onPointerDown={beginPan} onPointerMove={movePointer} onPointerUp={endPointer} onPointerCancel={() => { setPanStart(null); setMarkerDrag(null); setMarkerPreview(null); }}><div ref={stageRef} className="absolute inset-0 origin-center select-none" style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${scale})`, cursor: markerDrag !== null ? "grabbing" : panStart ? "grabbing" : isNarrator ? "crosshair" : "grab", backgroundImage: gridEnabled ? "linear-gradient(rgba(131,168,154,.32) 1px, transparent 1px), linear-gradient(90deg, rgba(131,168,154,.32) 1px, transparent 1px)" : undefined, backgroundSize: gridEnabled ? `${gridSize}px ${gridSize}px` : undefined }}>{selectedMap.imageUrl ? <img src={selectedMap.imageUrl} alt={`Mapa tático: ${selectedMap.title}`} draggable={false} className="pointer-events-none h-full w-full object-cover opacity-90" /> : <div className="pointer-events-none flex h-full items-center justify-center bg-[radial-gradient(circle_at_50%_45%,#28302c_0%,#121513_48%,#080908_100%)] p-8 text-center"><div><MapPinned className="mx-auto h-8 w-8 text-[#d27648]" /><p className="mt-4 font-serif text-2xl text-[#f4eee4]">Mapa sem imagem</p><p className="mt-2 max-w-xs text-sm leading-6 text-[#b8b3a8]">O tabuleiro já aceita grade e marcadores. Envie uma imagem tática quando estiver pronta.</p></div></div>}{selectedMap.markers.map((marker) => { const preview = markerPreview?.id === marker.id ? markerPreview : marker; return <button key={marker.id} type="button" onPointerDown={(event) => { if (!isNarrator) return; event.stopPropagation(); setMarkerDrag(marker.id); event.currentTarget.setPointerCapture(event.pointerId); }} className="absolute z-10 grid h-7 w-7 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-[#101211] text-[#101211] shadow-[0_0_0_1px_rgba(244,238,228,.75)] focus:outline-none focus:ring-2 focus:ring-[#f4eee4]" style={{ left: `${mapCoordinatePercent(preview.positionX)}%`, top: `${mapCoordinatePercent(preview.positionY)}%`, backgroundColor: marker.color, cursor: isNarrator ? "grab" : "default" }} aria-label={`${markerLabels[marker.markerType as MarkerType]}: ${marker.label}`} title={marker.label}><Crosshair className="h-3.5 w-3.5" /></button>; })}</div></div><p className="mt-3 flex items-center gap-2 text-[10px] leading-5 text-[#a9c7bb]"><Move className="h-3.5 w-3.5 shrink-0 text-[#d27648]" /> Arraste para panorâmica; use os controles ou a roda do mouse para zoom.{isNarrator ? " Clique no terreno para preparar um marcador; arraste um marcador para reposicioná-lo." : " Esta campanha está em modo de leitura para seu papel."}</p></div>
      <aside className="space-y-4"><div className="border border-white/10 bg-[#101211] p-4"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]">Configurar tabuleiro</p>{isNarrator ? <><Label htmlFor="map-title" className="mt-4 block text-[9px] font-bold uppercase tracking-[0.13em] text-[#a9c7bb]">Título</Label><Input id="map-title" value={draftTitle} onChange={(event) => setDraftTitle(event.target.value)} className="mt-2 h-10 rounded-none border-white/15 bg-[#171a18] text-[#eae3d5]" /><label className="mt-4 flex cursor-pointer items-center justify-between gap-3 text-sm text-[#eae3d5]"><span>Exibir grade</span><input type="checkbox" checked={gridEnabled} onChange={(event) => setGridEnabled(event.target.checked)} className="h-4 w-4 accent-[#b55b32]" /></label><div className="mt-4"><div className="flex justify-between text-[9px] font-bold uppercase tracking-[0.13em] text-[#a9c7bb]"><span>Passo da grade</span><span>{gridSize}px</span></div><Slider value={[gridSize]} onValueChange={([value]) => setGridSize(value)} min={20} max={240} step={5} className="mt-3" /></div><Button variant="outline" onClick={saveMap} disabled={updateMap.isPending} className="mt-5 h-10 w-full rounded-none border-[#83a89a]/55 text-[9px] font-bold uppercase tracking-[0.13em] text-[#d4ece2] hover:bg-[#83a89a]/15"><Save className="mr-2 h-3.5 w-3.5" />{updateMap.isPending ? "Salvando" : "Salvar mesa"}</Button><Label htmlFor="map-image" className="mt-3 flex h-10 cursor-pointer items-center justify-center border border-[#b55b32]/60 text-[9px] font-bold uppercase tracking-[0.13em] text-[#ffc1a5] hover:bg-[#b55b32]/15"><ImageUp className="mr-2 h-3.5 w-3.5" />{uploadImage.isPending ? "Enviando" : "Enviar imagem"}</Label><input id="map-image" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => chooseImage(event.target.files?.[0])} className="sr-only" disabled={uploadImage.isPending} /><p className="mt-2 text-[10px] leading-5 text-[#777d73]">PNG, JPEG ou WebP, até 4 MB.</p></> : <p className="mt-3 text-sm leading-6 text-[#b8b3a8]">As configurações são preservadas pelo narrador. Você pode navegar e consultar os marcadores.</p>}</div>
        {isNarrator ? <div className="border border-[#d27648]/40 bg-[#251714] p-4"><p className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.16em] text-[#ffc1a5]"><Sparkles className="h-3.5 w-3.5" /> Criar imagem procedural</p><p className="mt-2 text-[11px] leading-5 text-[#d4b9ad]">A geração usa OpenAI como rota principal e Gemini como contingência. Ela substitui a imagem atual; o upload manual continua disponível acima.</p>{selectedMap.imageProvider === "openai" || selectedMap.imageProvider === "gemini" ? <p className="mt-3 border-t border-[#d27648]/25 pt-3 text-[9px] font-bold uppercase tracking-[0.13em] text-[#ffd0bc]">Imagem atual gerada via {imageProviderLabels[selectedMap.imageProvider]}</p> : selectedMap.imageUrl ? <p className="mt-3 border-t border-[#d27648]/25 pt-3 text-[9px] font-bold uppercase tracking-[0.13em] text-[#d4b9ad]">Imagem atual enviada manualmente</p> : null}<Label htmlFor="map-creative-direction" className="mt-4 block text-[9px] font-bold uppercase tracking-[0.13em] text-[#ffc1a5]">Direção do terreno</Label><Textarea id="map-creative-direction" value={creativeDirection} onChange={(event) => setCreativeDirection(event.target.value)} placeholder="Ex.: ruínas costeiras alagadas, passarelas de madeira, névoa baixa e um farol quebrado" className="mt-2 min-h-24 rounded-none border-[#d27648]/35 bg-[#101211] text-sm text-[#f4eee4] placeholder:text-[#806963]" /><Label htmlFor="map-aspect-ratio" className="mt-3 block text-[9px] font-bold uppercase tracking-[0.13em] text-[#ffc1a5]">Proporção</Label><select id="map-aspect-ratio" value={aspectRatio} onChange={(event) => setAspectRatio(event.target.value as "16:9" | "4:3" | "1:1")} className="mt-2 h-9 w-full border border-[#d27648]/35 bg-[#101211] px-3 text-sm text-[#f4eee4] outline-none focus:border-[#d27648]"><option value="16:9">Panorâmico · 16:9</option><option value="4:3">Clássico · 4:3</option><option value="1:1">Quadrado · 1:1</option></select><Button type="button" onClick={createProceduralImage} disabled={generateImage.isPending || creativeDirection.trim().length < 12} className="mt-3 h-10 w-full rounded-none bg-[#d27648] text-[9px] font-bold uppercase tracking-[0.13em] text-[#101211] hover:bg-[#ef9670]"><Sparkles className="mr-2 h-3.5 w-3.5" />{generateImage.isPending ? "Gerando terreno" : "Gerar imagem do mapa"}</Button>{generationError ? <div role="alert" className="mt-3 border border-[#ffad98]/45 bg-[#3b1d19] p-3 text-xs leading-5 text-[#ffc1a5]">A geração não foi concluída. {generationError}<Button type="button" variant="outline" onClick={createProceduralImage} className="mt-2 h-8 w-full rounded-none border-[#ffad98]/45 text-[8px] font-bold uppercase tracking-[0.12em] text-[#ffded1]">Tentar novamente</Button></div> : null}</div> : null}
        {isNarrator && pendingPosition ? <div className="border border-[#b55b32]/55 bg-[#241714] p-4"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#ffc1a5]">Novo marcador · {mapCoordinatePercent(pendingPosition.x)}% / {mapCoordinatePercent(pendingPosition.y)}%</p><MarkerFields draft={markerDraft} setDraft={setMarkerDraft} prefix="new-marker" /><div className="mt-4 flex gap-2"><Button onClick={submitNewMarker} disabled={createMarker.isPending} className="h-10 flex-1 rounded-none bg-[#b55b32] text-[9px] font-bold uppercase tracking-[0.13em] text-[#101211] hover:bg-[#d27648]">{createMarker.isPending ? "Posicionando" : "Posicionar"}</Button><Button variant="outline" onClick={() => setPendingPosition(null)} className="h-10 rounded-none border-white/15 text-[9px] font-bold uppercase tracking-[0.13em] text-[#eae3d5]">Cancelar</Button></div></div> : null}
        {isNarrator && editingMarkerId ? <div className="border border-[#83a89a]/55 bg-[#14201b] p-4"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#c7e1d7]">Editar marcador</p><MarkerFields draft={markerDraft} setDraft={setMarkerDraft} prefix="edit-marker" /><div className="mt-4 flex gap-2"><Button onClick={saveMarker} disabled={updateMarker.isPending} className="h-10 flex-1 rounded-none bg-[#83a89a] text-[9px] font-bold uppercase tracking-[0.13em] text-[#101211] hover:bg-[#a9c7bb]">{updateMarker.isPending ? "Salvando" : "Salvar marcador"}</Button><Button variant="outline" onClick={() => setEditingMarkerId(null)} className="h-10 rounded-none border-white/15 text-[9px] font-bold uppercase tracking-[0.13em] text-[#eae3d5]">Cancelar</Button></div></div> : null}
        <div className="border border-white/10 bg-[#101211] p-4"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]">Marcadores · {selectedMap.markers.length}</p>{selectedMap.markers.length ? <div className="mt-3 space-y-2">{selectedMap.markers.map((marker) => <div key={marker.id} className="flex items-start justify-between gap-3 border-t border-white/10 pt-2"><div className="min-w-0"><p className="flex items-center gap-2 text-sm font-medium text-[#eae3d5]"><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ backgroundColor: marker.color }} />{marker.label}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[0.12em] text-[#83a89a]">{markerLabels[marker.markerType as MarkerType]}</p>{marker.description ? <p className="mt-1 text-xs leading-5 text-[#b8b3a8]">{marker.description}</p> : null}</div>{isNarrator ? <div className="flex shrink-0 gap-1"><Button variant="ghost" size="icon" onClick={() => beginMarkerEdit(marker)} aria-label={`Editar ${marker.label}`} className="h-7 w-7 rounded-none text-[#c7e1d7] hover:bg-[#83a89a]/15 hover:text-[#e3f6ee]"><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" onClick={() => removeMarker.mutate({ campaignId: activeCampaign.id, mapId: selectedMap.id, markerId: marker.id })} aria-label={`Remover ${marker.label}`} className="h-7 w-7 rounded-none text-[#ffad98] hover:bg-[#b55b32]/15 hover:text-[#ffd9cd]"><Trash2 className="h-3.5 w-3.5" /></Button></div> : null}</div>)}</div> : <p className="mt-3 text-sm leading-6 text-[#777d73]">Nenhum marcador nesta mesa.</p>}</div></aside>
    </div> : null}
  </section>;
}
