import { CalendarClock, Link2, LoaderCircle, Unlink } from "lucide-react";
import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export function CharacterShareLinkButton({ characterId }: { characterId: number | null }) {
  const [expiresAtInput, setExpiresAtInput] = useState("");
  const createLink = trpc.characters.createShareLink.useMutation({ onSuccess: async ({ token, expiresAt }) => { const link = `${window.location.origin}/compartilhar/ficha/${token}`; const expiryLabel = expiresAt ? ` Expira em ${new Date(expiresAt).toLocaleString("pt-BR")}.` : " Sem expiração definida."; try { await navigator.clipboard.writeText(link); toast.success(`Link exclusivo copiado.${expiryLabel}`); } catch { window.prompt("Copie o link exclusivo da ficha:", link); } }, onError: (error) => toast.error(error.message) });
  const revokeLink = trpc.characters.revokeShareLink.useMutation({ onSuccess: () => toast.success("Link exclusivo revogado."), onError: (error) => toast.error(error.message) });
  const create = () => { if (!characterId) { toast.error("Salve a ficha antes de gerar um link exclusivo."); return; } const expiresAt = expiresAtInput ? new Date(expiresAtInput) : null; if (expiresAt && (Number.isNaN(expiresAt.getTime()) || expiresAt <= new Date())) { toast.error("Escolha uma data e hora futuras para a expiração."); return; } createLink.mutate({ characterId, expiresAt }); };
  return <div className="flex flex-wrap items-end justify-end gap-2"><label className="flex min-w-48 flex-col gap-1 text-[8px] font-bold uppercase tracking-[0.12em] text-[#a9c7bb]">Expiração opcional<input aria-label="Expiração do link" type="datetime-local" min={new Date().toISOString().slice(0, 16)} value={expiresAtInput} onChange={(event) => setExpiresAtInput(event.target.value)} className="h-11 border border-white/20 bg-[#101211] px-2 text-xs normal-case tracking-normal text-[#f4eee4] focus:border-[#83a89a]" /></label><Button onClick={create} disabled={createLink.isPending} variant="outline" className="h-11 rounded-none border-[#83a89a]/60 bg-[#83a89a]/10 text-[10px] font-bold uppercase tracking-[0.14em] text-[#f4eee4] hover:bg-[#83a89a]/20">{createLink.isPending ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Link2 className="mr-2 h-4 w-4" />}{createLink.isPending ? "Gerando link" : "Gerar link"}</Button><Button onClick={() => characterId && revokeLink.mutate({ characterId })} disabled={!characterId || revokeLink.isPending} variant="outline" aria-label="Revogar link da ficha" className="h-11 w-11 rounded-none border-white/20 text-[#ffb08e] hover:border-[#b55b32] hover:text-[#ffb08e]">{revokeLink.isPending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Unlink className="h-4 w-4" />}</Button><p className="basis-full text-right text-[9px] leading-4 text-[#a9c7bb]"><CalendarClock className="mr-1 inline h-3.5 w-3.5" />Deixe em branco para manter o acesso até revogar ou gerar outro link.</p></div>;
}
