import React, { useState } from "react";
import { BookmarkPlus, LoaderCircle, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type SystemId = "vampiro-v5" | "o-um-anel";

export function CustomArchetypePanel({ systemId, snapshot, onApply }: { systemId: SystemId; snapshot: Record<string, unknown>; onApply: (payload: Record<string, unknown>, title: string) => void }) {
  const utils = trpc.useUtils();
  const { data: archetypes = [], isLoading, error, refetch } = trpc.archetypes.mine.useQuery({ systemId });
  const [title, setTitle] = useState("");
  const [summary, setSummary] = useState("");
  const create = trpc.archetypes.create.useMutation({ onSuccess: async () => { await utils.archetypes.mine.invalidate({ systemId }); setTitle(""); setSummary(""); toast.success("Arquétipo salvo no seu arquivo."); }, onError: (error) => toast.error(error.message) });
  const remove = trpc.archetypes.remove.useMutation({ onSuccess: async () => { await utils.archetypes.mine.invalidate({ systemId }); toast.success("Arquétipo removido."); }, onError: (error) => toast.error(error.message) });
  const save = () => { if (title.trim().length < 2) { toast.error("Dê um nome ao arquétipo antes de salvá-lo."); return; } create.mutate({ systemId, title: title.trim(), summary: summary.trim() || undefined, payload: snapshot }); };

  return <article className="border border-[#83a89a]/35 bg-[#171a18] p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[9px] font-bold uppercase tracking-[0.15em] text-[#a9c7bb]">Arquétipos próprios</p><h3 className="mt-1 font-serif text-2xl text-[#f4eee4]">Guarde sua combinação favorita.</h3></div><p className="max-w-sm text-xs leading-5 text-[#b8b3a8]">O retrato atual de atributos e perícias será salvo para reutilização nesta conta.</p></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1.4fr_auto]"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: Investigadora do Elysium" className="h-10 border border-white/15 bg-[#101211] px-3 text-sm text-[#f4eee4] placeholder:text-[#777c73]" /><input value={summary} onChange={(event) => setSummary(event.target.value)} placeholder="Uma nota curta sobre o estilo" className="h-10 border border-white/15 bg-[#101211] px-3 text-sm text-[#f4eee4] placeholder:text-[#777c73]" /><Button onClick={save} disabled={create.isPending} className="h-10 rounded-none bg-[#83a89a] text-[9px] font-bold uppercase tracking-[0.12em] text-[#161715] hover:bg-[#a9c7bb]">{create.isPending ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <BookmarkPlus className="mr-2 h-4 w-4" />} Salvar</Button></div><div className="mt-4 grid gap-2">{isLoading ? <p className="text-xs text-[#a9c7bb]">Consultando arquétipos preservados…</p> : error ? <div className="flex flex-wrap items-center justify-between gap-3 border border-[#b55b32]/55 bg-[#3b1d19]/45 p-3 text-xs text-[#ffb09d]"><span>Não foi possível carregar os arquétipos agora.</span><Button onClick={() => refetch()} variant="outline" size="sm" className="h-8 rounded-none border-[#ffb08e]/40 text-[9px] font-bold uppercase tracking-[0.1em] text-[#ffb08e]">Tentar novamente</Button></div> : archetypes.length ? archetypes.map((archetype) => <div key={archetype.id} className="flex flex-col justify-between gap-3 border border-white/10 bg-black/10 p-3 sm:flex-row sm:items-center"><div><p className="font-serif text-lg text-[#f4eee4]">{archetype.title}</p>{archetype.summary ? <p className="mt-1 text-xs text-[#b8b3a8]">{archetype.summary}</p> : null}</div><div className="flex gap-2"><Button onClick={() => onApply(archetype.payload, archetype.title)} variant="outline" size="sm" className="h-8 rounded-none border-[#83a89a]/45 text-[9px] font-bold uppercase tracking-[0.1em] text-[#f4eee4]">Aplicar</Button><Button onClick={() => remove.mutate({ archetypeId: archetype.id })} disabled={remove.isPending} size="icon" variant="outline" aria-label={`Excluir ${archetype.title}`} className="h-8 w-8 rounded-none border-white/15 text-[#ffb08e]"><Trash2 className="h-3.5 w-3.5" /></Button></div></div>) : <p className="text-xs leading-5 text-[#b8b3a8]">Nenhum arquétipo próprio salvo ainda. Ajuste a ficha e guarde uma combinação para reutilizá-la.</p>}</div></article>;
}
