import { ShieldAlert, Sparkles } from "lucide-react";
import React from "react";

export function DiceRollFeedback({ dice, modifier, children }: { dice: number[]; modifier: number; children: React.ReactNode }) {
  const hasConditionImpact = modifier !== 0;
  return <article aria-live="polite" className={`roll-result-announce border bg-[#101211] p-4 ${hasConditionImpact ? "condition-impact border-[#d27648]/70" : "border-[#83a89a]/45"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div>{children}</div><Sparkles className="h-4 w-4 text-[#d27648]" aria-hidden="true" /></div><div className="mt-3 flex flex-wrap gap-2">{dice.map((die, index) => <span key={`${die}-${index}`} className="vtm-die-result grid h-9 w-9 place-items-center border border-[#83a89a]/60 bg-[#17211d] font-mono text-sm font-bold text-[#f4eee4]" style={{ animationDelay: `${index * 55}ms` }}>{die}</span>)}</div>{hasConditionImpact ? <p className={`mt-3 flex items-center gap-2 border-t pt-3 text-xs font-semibold ${modifier > 0 ? "border-[#83a89a]/35 text-[#9dccb8]" : "border-[#b55b32]/35 text-[#ffb08e]"}`}><ShieldAlert className="h-4 w-4" />Condição temporária aplicada: {modifier > 0 ? "+" : ""}{modifier} na resolução final.</p> : <p className="mt-3 border-t border-white/10 pt-3 text-xs text-[#a9c7bb]">Nenhuma condição temporária alterou esta rolagem.</p>}</article>;
}

export function DiceRollInProgress({ label, diceCount, modifier }: { label: string; diceCount: number; modifier: number }) {
  return <article aria-live="assertive" className="roll-result-announce border border-[#d27648]/55 bg-[#101211] p-4"><div className="flex items-center justify-between gap-3"><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-[#ffb08e]">{label} · lançando dados</p><Sparkles className="h-4 w-4 animate-spin text-[#d27648]" /></div><div className="mt-3 flex flex-wrap gap-2">{Array.from({ length: Math.min(12, Math.max(1, diceCount)) }, (_, index) => <span key={index} className="vtm-die-rolling grid h-9 w-9 place-items-center border border-[#d27648]/55 bg-[#3b1d19]/55 font-mono text-sm font-bold text-[#ffb08e]" style={{ animationDelay: `${index * 40}ms` }}>?</span>)}</div>{modifier !== 0 ? <p className="mt-3 text-xs text-[#a9c7bb]">A condição {modifier > 0 ? "+" : ""}{modifier} será aplicada ao resultado.</p> : null}</article>;
}
