import { History, LoaderCircle } from "lucide-react";
import React from "react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { trpc } from "@/lib/trpc";

export function DiceRollHistorySheet({ characterId, characterName }: { characterId: number | null; characterName: string }) {
  const { data: rolls = [], isLoading, error } = trpc.characters.rollHistory.useQuery({ characterId: characterId || 0 }, { enabled: !!characterId });
  return <Sheet><SheetTrigger asChild><Button disabled={!characterId} variant="outline" className="h-11 rounded-none border-white/20 bg-transparent text-[10px] font-bold uppercase tracking-[0.13em] text-[#a9c7bb] hover:border-[#83a89a] hover:text-[#f4eee4]"><History className="mr-2 h-4 w-4" /> Histórico de dados</Button></SheetTrigger><SheetContent className="w-full overflow-y-auto border-l border-[#83a89a]/35 bg-[#101211] text-[#eae3d5] sm:max-w-md"><SheetHeader><SheetTitle className="font-serif text-3xl text-[#f4eee4]">Histórico completo</SheetTitle><SheetDescription className="text-[#b8b3a8]">{characterName ? `Todas as rolagens preservadas de ${characterName}.` : "Selecione uma ficha preservada para consultar as rolagens."}</SheetDescription></SheetHeader><div className="mt-7 space-y-3">{isLoading ? <p className="flex items-center gap-2 text-sm text-[#a9c7bb]"><LoaderCircle className="h-4 w-4 animate-spin" /> Consultando o arquivo…</p> : error ? <p className="border border-[#b55b32]/50 bg-[#3b1d19]/45 p-3 text-sm text-[#ffb08e]">Não foi possível carregar as rolagens agora.</p> : !rolls.length ? <p className="border border-white/10 bg-black/10 p-4 text-sm leading-6 text-[#b8b3a8]">Nenhuma rolagem foi registrada para esta ficha.</p> : rolls.map((roll) => { const result = roll.resultData as Record<string, unknown>; const dice = Array.isArray(result.dice) ? result.dice : Array.isArray(result.skillDice) ? result.skillDice : []; return <article key={roll.id} className="border border-white/10 bg-[#171a18] p-4"><p className="text-[9px] font-bold uppercase tracking-[0.13em] text-[#a9c7bb]">{new Date(roll.createdAt).toLocaleString("pt-BR")}</p><h3 className="mt-2 font-serif text-xl text-[#f4eee4]">{roll.context || "Rolagem"}</h3><p className="mt-2 text-sm text-[#c7c1b5]">{typeof result.successes === "number" ? `${result.successes} sucesso(s)` : "Resultado registrado"}{typeof result.pool === "number" ? ` · reserva ${result.pool}` : ""}{typeof result.target === "number" ? ` · alvo ${result.target}` : ""}</p>{dice.length ? <p className="mt-3 font-mono text-xs tracking-[0.14em] text-[#a9c7bb]">{dice.join(" · ")}</p> : null}</article>; })}</div></SheetContent></Sheet>;
}
