import { Minus, Plus, ShieldAlert, Trash2 } from "lucide-react";
import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import type { TemporaryModifier } from "@shared/vampire-v5";

export function getTemporaryModifierTotal(modifiers: TemporaryModifier[], scope: "attributes" | "skills" | "test") {
  return modifiers.filter((modifier) => modifier.enabled && (modifier.scope === "all" || modifier.scope === scope || (scope === "test" && (modifier.scope === "attributes" || modifier.scope === "skills")))).reduce((total, modifier) => total + modifier.value, 0);
}

export function TemporaryModifiersPanel({ modifiers, onChange }: { modifiers: TemporaryModifier[]; onChange: (next: TemporaryModifier[]) => void }) {
  const [label, setLabel] = useState("");
  const [value, setValue] = useState(1);
  const [scope, setScope] = useState<TemporaryModifier["scope"]>("all");
  const add = () => { if (label.trim().length < 2) return; onChange([...modifiers, { id: `mod-${Date.now().toString(36)}`, label: label.trim(), value: Math.max(-10, Math.min(10, value || 0)), scope, enabled: true }]); setLabel(""); setValue(1); setScope("all"); };
  return <article className="border border-[#d27648]/45 bg-[#171a18] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#ffb08e]"><ShieldAlert className="h-4 w-4 text-[#d27648]" /> Condições temporárias</div><p className="mt-2 text-xs leading-5 text-[#b8b3a8]">Bônus e penalidades ativos entram nas rolagens até serem desativados ou removidos.</p><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_80px_150px_auto]"><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Ex.: Ferido, ajuda de aliado" className="h-10 border border-white/15 bg-[#101211] px-3 text-sm text-[#f4eee4]" /><input aria-label="Valor do modificador" type="number" min="-10" max="10" value={value} onChange={(event) => setValue(Number(event.target.value))} className="h-10 border border-white/15 bg-[#101211] px-2 text-center text-sm text-[#f4eee4]" /><select value={scope} onChange={(event) => setScope(event.target.value as TemporaryModifier["scope"])} className="h-10 border border-white/15 bg-[#101211] px-2 text-xs text-[#f4eee4]"><option value="all">Todos os testes</option><option value="attributes">Atributos</option><option value="skills">Habilidades</option></select><Button onClick={add} className="h-10 rounded-none bg-[#d27648] text-[#161715] hover:bg-[#ffb08e]"><Plus className="h-4 w-4" /></Button></div><div className="mt-4 grid gap-2">{modifiers.length ? modifiers.map((modifier) => <div key={modifier.id} className={`flex flex-wrap items-center justify-between gap-3 border p-3 ${modifier.enabled ? "border-[#d27648]/45 bg-[#d27648]/[0.06]" : "border-white/10 bg-black/10 opacity-55"}`}><label className="flex items-center gap-3 text-sm text-[#f4eee4]"><input type="checkbox" checked={modifier.enabled} onChange={() => onChange(modifiers.map((item) => item.id === modifier.id ? { ...item, enabled: !item.enabled } : item))} className="accent-[#d27648]" /><span>{modifier.label}</span><strong className={modifier.value >= 0 ? "text-[#9dccb8]" : "text-[#ffb08e]"}>{modifier.value >= 0 ? "+" : ""}{modifier.value}</strong><span className="text-[9px] font-bold uppercase tracking-[0.12em] text-[#a9c7bb]">{modifier.scope === "all" ? "geral" : modifier.scope === "attributes" ? "atributos" : "habilidades"}</span></label><Button onClick={() => onChange(modifiers.filter((item) => item.id !== modifier.id))} size="icon" variant="outline" aria-label={`Remover ${modifier.label}`} className="h-8 w-8 rounded-none border-white/15 text-[#ffb08e]"><Trash2 className="h-3.5 w-3.5" /></Button></div>) : <p className="text-xs text-[#b8b3a8]">Nenhuma condição ativa. Adicione efeitos como ferimento, cobertura ou auxílio.</p>}</div></article>;
}
