import React from "react";
import { Droplets, Heart, Moon, Shield, Sparkles } from "lucide-react";
import type { V5SheetData } from "@shared/vampire-v5";

type V5IdentityProps = { sheet: V5SheetData; onChange: (patch: Partial<V5SheetData>) => void; selectedClanName?: string };

function Track({ label, value, max, accent = "#d27648", onChange }: { label: string; value: number; max: number; accent?: string; onChange: (value: number) => void }) {
  return <label className="block"><span className="flex items-center justify-between text-[9px] font-bold uppercase tracking-[.14em] text-[#a9c7bb]"><span>{label}</span><strong className="text-[#f4eee4]">{value}/{max}</strong></span><input aria-label={label} type="range" min={0} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-3 h-1.5 w-full cursor-pointer appearance-none bg-white/15" style={{ accentColor: accent }} /></label>;
}

export function V5CoreSheetPanel({ sheet, onChange, selectedClanName }: V5IdentityProps) {
  return <section aria-label="Núcleo da ficha de Vampiro V5" className="relative overflow-hidden border border-[#b55b32]/60 bg-[#171a18] p-5 sm:p-6"><div className="absolute -right-10 -top-10 h-36 w-36 rounded-full border border-[#b55b32]/20" /><div className="relative"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-white/10 pb-4"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#d27648]"><Droplets className="h-4 w-4" /> Folha de sangue · V5</p><h2 className="mt-2 font-serif text-3xl text-[#f4eee4]">O vampiro em foco</h2></div><p className="text-right text-[9px] font-bold uppercase tracking-[.12em] text-[#83a89a]">{selectedClanName || "Clã não definido"}</p></div><div className="mt-5 grid gap-5 md:grid-cols-3"><Track label="Fome" value={sheet.hunger} max={5} onChange={(value) => onChange({ hunger: value })} /><Track label="Humanidade" value={sheet.humanity} max={10} accent="#83a89a" onChange={(value) => onChange({ humanity: value })} /><div className="grid grid-cols-2 gap-3"><div className="border border-white/10 bg-black/10 p-3"><span className="text-[9px] font-bold uppercase tracking-[.12em] text-[#8f958c]">Potência de sangue</span><strong className="mt-2 block font-serif text-2xl text-[#f4eee4]">{sheet.bloodPotency}</strong></div><div className="border border-white/10 bg-black/10 p-3"><span className="text-[9px] font-bold uppercase tracking-[.12em] text-[#8f958c]">Geração</span><strong className="mt-2 block font-serif text-2xl text-[#f4eee4]">{sheet.generation}</strong></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="flex items-center gap-3 border-l-2 border-[#d27648] pl-3"><Shield className="h-4 w-4 text-[#d27648]" /><span className="text-xs text-[#b8b3a8]">Vitalidade<br /><strong className="text-[#f4eee4]">calculada pela ficha</strong></span></div><div className="flex items-center gap-3 border-l-2 border-[#83a89a] pl-3"><Sparkles className="h-4 w-4 text-[#83a89a]" /><span className="text-xs text-[#b8b3a8]">Força de Vontade<br /><strong className="text-[#f4eee4]">calculada pela ficha</strong></span></div><div className="flex items-center gap-3 border-l-2 border-white/20 pl-3"><Moon className="h-4 w-4 text-[#a9c7bb]" /><span className="text-xs text-[#b8b3a8]">Bane e compulsão<br /><strong className="text-[#f4eee4]">consulte o clã</strong></span></div></div></div></section>;
}

type OneRingIdentityProps = { endurance: number; hope: number; shadow: number; load: number; onChange: (patch: { endurance?: number; hope?: number; shadow?: number; load?: number }) => void };

export function OneRingCoreSheetPanel({ endurance, hope, shadow, load, onChange }: OneRingIdentityProps) {
  return <section aria-label="Núcleo da ficha de O Um Anel" className="relative overflow-hidden border border-[#83a89a]/60 bg-[#171a18] p-5 sm:p-6"><div className="relative"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-white/10 pb-4"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#83a89a]"><Heart className="h-4 w-4 text-[#d27648]" /> Folha da jornada · 2ª edição</p><h2 className="mt-2 font-serif text-3xl text-[#f4eee4]">O companheiro na estrada</h2></div><span className="text-[9px] font-bold uppercase tracking-[.12em] text-[#a9c7bb]">Recursos centrais</span></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><label className="border border-white/10 bg-black/10 p-3"><span className="text-[9px] font-bold uppercase tracking-[.12em] text-[#8f958c]">Resistência</span><input aria-label="Resistência" type="number" min={0} value={endurance} onChange={(event) => onChange({ endurance: Math.max(0, Number(event.target.value)) })} className="mt-2 h-9 w-full border border-white/15 bg-[#101211] px-2 text-right text-lg text-[#f4eee4]" /></label><label className="border border-white/10 bg-black/10 p-3"><span className="text-[9px] font-bold uppercase tracking-[.12em] text-[#8f958c]">Esperança</span><input aria-label="Esperança" type="number" min={0} value={hope} onChange={(event) => onChange({ hope: Math.max(0, Number(event.target.value)) })} className="mt-2 h-9 w-full border border-white/15 bg-[#101211] px-2 text-right text-lg text-[#f4eee4]" /></label><label className="border border-white/10 bg-black/10 p-3"><span className="text-[9px] font-bold uppercase tracking-[.12em] text-[#8f958c]">Sombra</span><input aria-label="Sombra" type="number" min={0} value={shadow} onChange={(event) => onChange({ shadow: Math.max(0, Number(event.target.value)) })} className="mt-2 h-9 w-full border border-[#b55b32]/40 bg-[#101211] px-2 text-right text-lg text-[#ffb08e]" /></label><label className="border border-white/10 bg-black/10 p-3"><span className="text-[9px] font-bold uppercase tracking-[.12em] text-[#8f958c]">Carga</span><input aria-label="Carga" type="number" min={0} value={load} onChange={(event) => onChange({ load: Math.max(0, Number(event.target.value)) })} className="mt-2 h-9 w-full border border-white/15 bg-[#101211] px-2 text-right text-lg text-[#f4eee4]" /></label></div><p className="mt-4 border-l-2 border-[#d27648] pl-3 text-xs leading-5 text-[#b8b3a8]">A resistência mede o fôlego do companheiro; Esperança e Sombra registram o custo moral da jornada. A Carga alimenta o estado de cansaço.</p></div></section>;
}
