import { HeartPulse, Minus, Plus, ShieldAlert } from "lucide-react";
import React from "react";
import { calculateIntegrityTrack } from "@shared/rules-engine";

type Damage = { superficial: number; aggravated: number };

export function V5IntegrityPanel({ maximum, damage, onChange }: { maximum: number; damage: Damage; onChange: (damage: Damage) => void }) {
  const track = calculateIntegrityTrack(maximum, damage.superficial, damage.aggravated);
  const setDamage = (kind: keyof Damage, delta: number) => {
    const current = damage[kind];
    const next = Math.max(0, Math.min(maximum, current + delta));
    const candidate = { ...damage, [kind]: next };
    const normalized = calculateIntegrityTrack(maximum, candidate.superficial, candidate.aggravated);
    onChange({ superficial: normalized.superficial, aggravated: normalized.aggravated });
  };
  return <article className={`border p-5 ${track.impaired ? "border-[#d27648]/80 bg-[#3b1d19]/55" : "border-[#83a89a]/35 bg-[#171a18]"}`}><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a9c7bb]"><HeartPulse className="h-4 w-4 text-[#d27648]" /> Integridade</p><h2 className="mt-2 font-serif text-3xl leading-none text-[#f4eee4]">{track.remaining}/{track.maximum}</h2><p className="mt-2 text-xs leading-5 text-[#b8b3a8]">Vitalidade restante · superficial preenche a trilha, agravado ocupa espaço permanente.</p></div>{track.impaired ? <ShieldAlert className="h-6 w-6 shrink-0 text-[#ffb08e]" aria-label="Integridade comprometida" /> : null}</div><div className="mt-4 flex gap-1" aria-label="Trilha de integridade">{Array.from({ length: track.maximum }, (_, index) => <span key={index} className={`h-3 flex-1 border border-black/25 ${index < track.aggravated ? "bg-[#a84337]" : index < track.occupied ? "bg-[#d27648]" : "bg-white/10"}`} />)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="flex items-center justify-between border border-white/10 bg-black/10 p-2"><span className="text-xs text-[#d8d1c5]">Dano superficial <strong className="ml-1 text-[#f4eee4]">{track.superficial}</strong></span><span className="flex gap-1"><button type="button" aria-label="Reduzir dano superficial" onClick={() => setDamage("superficial", -1)} className="grid h-7 w-7 place-items-center border border-white/15 text-[#a9c7bb]"><Minus className="h-3.5 w-3.5" /></button><button type="button" aria-label="Adicionar dano superficial" onClick={() => setDamage("superficial", 1)} className="grid h-7 w-7 place-items-center border border-[#d27648]/60 text-[#ffb08e]"><Plus className="h-3.5 w-3.5" /></button></span></div><div className="flex items-center justify-between border border-white/10 bg-black/10 p-2"><span className="text-xs text-[#d8d1c5]">Dano agravado <strong className="ml-1 text-[#f4eee4]">{track.aggravated}</strong></span><span className="flex gap-1"><button type="button" aria-label="Reduzir dano agravado" onClick={() => setDamage("aggravated", -1)} className="grid h-7 w-7 place-items-center border border-white/15 text-[#a9c7bb]"><Minus className="h-3.5 w-3.5" /></button><button type="button" aria-label="Adicionar dano agravado" onClick={() => setDamage("aggravated", 1)} className="grid h-7 w-7 place-items-center border border-[#d27648]/60 text-[#ffb08e]"><Plus className="h-3.5 w-3.5" /></button></span></div></div>{track.impaired ? <p className="mt-4 border-t border-[#ffb08e]/25 pt-3 text-xs leading-5 text-[#ffded1]">A trilha está preenchida: o motor aplica <strong>−2 dados</strong> às rolagens até que a integridade seja recuperada.</p> : <p className="mt-4 border-t border-white/10 pt-3 text-[10px] text-[#a9c7bb]">A penalidade só é aplicada automaticamente quando toda a trilha estiver preenchida.</p>}</article>;
}
